import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { CustomerIdentity, CustomerIdentityEvidence, CustomerEvidenceType } from "@/features/customer-identity/customer-identity.types";
function identity(row: Record<string, unknown>): CustomerIdentity { return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: String(row.project_id), phoneE164: row.phone_e164 ? String(row.phone_e164) : undefined, phoneHash: row.phone_hash ? String(row.phone_hash) : undefined, emailNormalized: row.email_normalized ? String(row.email_normalized) : undefined, emailHash: row.email_hash ? String(row.email_hash) : undefined, externalCustomerId: row.external_customer_id ? String(row.external_customer_id) : undefined, firstSeenAt: String(row.first_seen_at), lastSeenAt: String(row.last_seen_at), metadata: (row.metadata || {}) as Record<string, unknown> }; }
function evidence(row: Record<string, unknown>): CustomerIdentityEvidence { return { id: String(row.id), customerIdentityId: String(row.customer_identity_id), projectId: String(row.project_id), evidenceType: row.evidence_type as CustomerEvidenceType, sourceType: row.source_type ? String(row.source_type) : undefined, sourceId: row.source_id ? String(row.source_id) : undefined, occurredAt: String(row.occurred_at), metadata: (row.metadata || {}) as Record<string, unknown> }; }
export class CustomerIdentityRepository { constructor(private readonly database: SupabaseClient) {}
  async find(projectId: string, phoneHash?: string, emailHash?: string,externalCustomerId?:string) { let query = this.database.from("customer_identities").select("*").eq("project_id", projectId); if (phoneHash) query = query.eq("phone_hash", phoneHash); else if (emailHash) query = query.eq("email_hash", emailHash); else if(externalCustomerId)query=query.eq("external_customer_id",externalCustomerId);else return null; const { data, error } = await query.maybeSingle(); if (error) throw error; return data ? identity(data) : null; }
  async create(input: { workspaceId: string; projectId: string; phoneE164?: string; phoneHash?: string; emailNormalized?: string; emailHash?: string;externalCustomerId?:string }) { const { data, error } = await this.database.from("customer_identities").insert({ workspace_id: input.workspaceId, project_id: input.projectId, phone_e164: input.phoneE164 || null, phone_hash: input.phoneHash || null, email_normalized: input.emailNormalized || null, email_hash: input.emailHash || null,external_customer_id:input.externalCustomerId||null }).select("*").single(); if (error) throw error; return identity(data); }
  async touch(id: string, input: { emailNormalized?: string; emailHash?: string }) { await this.database.from("customer_identities").update({ last_seen_at: new Date().toISOString(), email_normalized: input.emailNormalized || undefined, email_hash: input.emailHash || undefined }).eq("id", id); }
  async evidence(customerIdentityId: string) { const { data, error } = await this.database.from("customer_identity_evidence").select("*").eq("customer_identity_id", customerIdentityId).order("occurred_at", { ascending: false }); if (error) throw error; return (data || []).map(evidence); }
  async addEvidence(input: { customerIdentityId: string; projectId: string; evidenceType: CustomerEvidenceType; sourceType?: string; sourceId?: string; metadata?: Record<string, unknown> }) { if (input.sourceType && input.sourceId) { const { data: existing } = await this.database.from("customer_identity_evidence").select("*").eq("customer_identity_id", input.customerIdentityId).eq("evidence_type", input.evidenceType).eq("source_type", input.sourceType).eq("source_id", input.sourceId).maybeSingle(); if (existing) return evidence(existing); } const { data, error } = await this.database.from("customer_identity_evidence").insert({ customer_identity_id: input.customerIdentityId, project_id: input.projectId, evidence_type: input.evidenceType, source_type: input.sourceType || null, source_id: input.sourceId || null, metadata: input.metadata || {} }).select("*").single(); if (error) throw error; return evidence(data); }
}
