import Link from "next/link";
import { BarChart3, Route, Sparkles } from "lucide-react";
import { Brand } from "@/components/ui/brand";

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return <main className="grid min-h-screen bg-white lg:grid-cols-[1.05fr_.95fr]">
    <section className="flex min-h-screen flex-col px-6 py-7 sm:px-10 lg:px-16"><Brand /><div className="mx-auto my-auto w-full max-w-[430px] py-12">{children}</div><p className="text-center text-xs text-[#9797a0]">Ao continuar, você concorda com os termos e a política de privacidade.</p></section>
    <section className="relative hidden overflow-hidden bg-[#18171e] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="dot-grid absolute inset-0 text-white/[.055]" /><div className="absolute -right-20 top-10 size-80 rounded-full bg-[#705ee9]/30 blur-3xl" /><div className="absolute -bottom-32 left-10 size-96 rounded-full bg-[#f06d5b]/20 blur-3xl" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-2 text-xs font-bold text-[#c8c3ff]"><Sparkles size={14} /> A bio que entende, recomenda e vende</span><blockquote className="mt-12 max-w-xl text-5xl font-extrabold leading-[1.04] tracking-[-.055em]">“Nosso link deixou de ser uma lista e virou a melhor conversa antes da conversa.”</blockquote></div><div className="relative grid grid-cols-2 gap-4"><div className="rounded-[22px] border border-white/10 bg-white/[.055] p-5"><Route className="text-[#a79df9]" /><strong className="mt-7 block text-2xl">68%</strong><span className="text-sm text-white/55">concluem a jornada</span></div><div className="rounded-[22px] border border-white/10 bg-white/[.055] p-5"><BarChart3 className="text-[#ff8c79]" /><strong className="mt-7 block text-2xl">2,4×</strong><span className="text-sm text-white/55">mais leads qualificados</span></div></div><Link href="/" className="relative mt-10 text-sm font-semibold text-white/55 hover:text-white">← Voltar ao início</Link></section>
  </main>;
}
