import { AdminPeriod, MetricStrip } from "@/components/platform-admin/admin-metrics";
import { createServiceClient } from "@/lib/supabase/server";
import { getAdminProductMetrics } from "@/server/product-metrics/admin-product-metrics";

const duration = (value: number | null) => value == null ? "—" : value < 3_600_000 ? `${Math.round(value / 60_000)} min` : `${Math.round(value / 3_600_000)} h`;
const percent = (part: number, total: number) => total ? `${Math.round(part * 1000 / total) / 10}%` : "—";

export default async function ProductMetricsPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const query = await searchParams;
  const days = [7, 30, 90].includes(Number(query.days)) ? Number(query.days) : 30;
  const metrics = await getAdminProductMetrics(createServiceClient()!, days);
  const a = metrics.activation, u = metrics.usage, w = metrics.wtp;
  const stage = (key: string) => Number(a[key as keyof typeof a] || 0);
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-extrabold tracking-[-.03em]">Produto</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#667487]">Activation, Usage, Conversion e Willingness to Pay calculados com eventos first-party e resultados confirmados.</p></div><AdminPeriod current={days} path="/admin/product" /></div>
    <section className="mt-8"><h2 className="text-xl font-extrabold">Activation Quality</h2><MetricStrip items={[{ label: "Cadastros", value: stage("account_created") }, { label: "Primeira estrutura", value: stage("first_structure_generated") }, { label: "Primeira publicação", value: stage("first_project_published") }, { label: "Primeiro tráfego", value: stage("first_traffic_received") }, { label: "Primeira oportunidade", value: stage("first_opportunity_generated") }, { label: "Primeira conversão", value: stage("first_conversion_confirmed") }]} /><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Conta → estrutura", duration(a.medianAccountToStructureMs)], ["Estrutura → publicação", duration(a.medianStructureToPublishedMs)], ["Conta → publicação", duration(a.medianAccountToPublishedMs)], ["Publicação → tráfego", duration(a.medianPublishedToTrafficMs)], ["Tráfego → oportunidade", duration(a.medianTrafficToOpportunityMs)]].map(([label, value]) => <div key={label} className="border border-[#dfe6ee] bg-white p-4"><span className="text-xs font-bold text-[#667487]">{label}</span><strong className="mt-2 block text-xl">{value}</strong></div>)}</div></section>
    <section className="mt-10"><h2 className="text-xl font-extrabold">Usage</h2><MetricStrip items={[{ label: "Workspaces publicados", value: u.publishedWorkspaces }, { label: "Retornaram ao produto", value: u.returnedWorkspaces }, { label: "Abriram analytics", value: u.analyticsViewed }, { label: "Abriram otimização", value: u.optimizationViewed }, { label: "Confirmaram conversão", value: u.conversionConfirmed }]} /><p className="mt-3 text-sm text-[#667487]">Retorno após publicação: {percent(u.returnedWorkspaces, u.publishedWorkspaces)} · Analytics visto: {percent(u.analyticsViewed, u.publishedWorkspaces)} · Otimização vista: {percent(u.optimizationViewed, u.publishedWorkspaces)}.</p></section>
    <section className="mt-10"><h2 className="text-xl font-extrabold">Willingness to Pay</h2><MetricStrip items={[{ label: "Trials", value: w.trialStarted }, { label: "Paywall visto", value: w.paywallViewed }, { label: "Checkout iniciado", value: w.checkoutStarted }, { label: "Pagantes", value: w.paid }, { label: "Pagantes com oportunidade", value: w.valueExposedPaid }]} /><div className="mt-4 overflow-x-auto border border-[#dfe6ee] bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b bg-[#f7f8fa] text-[#536178]"><th className="p-4">Exposição a valor no trial</th><th>Workspaces</th></tr></thead><tbody>{[["Sem tráfego", w.noTraffic], ["Tráfego sem oportunidade", w.trafficWithoutOpportunity], ["Com oportunidade", w.withOpportunity], ["Com conversão confirmada", w.withConfirmedConversion]].map(([label, value]) => <tr key={label} className="border-b last:border-0"><td className="p-4 font-bold">{label}</td><td>{value}</td></tr>)}</tbody></table></div></section>
  </div>;
}
