"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- editors operate on content already validated by the section-specific Zod registry */

import { Plus, Trash2 } from "lucide-react";
import type { Project } from "@/types";
import type { PresenceAction, PresencePage, PresenceSection, PresenceSectionType } from "@/features/presence/presence.types";

interface EditorProps { project: Project; page: PresencePage; section: PresenceSection; onChange(section: PresenceSection): void }
const input = "mt-1 min-h-10 w-full rounded-xl border border-[#dedce7] bg-white px-3 text-sm outline-none focus:border-[#786be2] focus:ring-4 focus:ring-[#786be2]/10";
const label = "block text-xs font-extrabold text-[#55515e]";
function patchContent(props: EditorProps, patch: Record<string, unknown>) { props.onChange({ ...props.section, content: { ...props.section.content, ...patch } }); }

function ActionEditor({ project, page, action, onChange, labelText = "Ação" }: { project: Project; page: PresencePage; action?: PresenceAction; onChange(action?: PresenceAction): void; labelText?: string }) {
  const current = action || { type: "start_conversion_goal", label: "Começar", conversionGoalId: project.conversionGoals?.find((goal) => goal.isActive)?.id, style: "primary" } satisfies PresenceAction;
  return <fieldset className="rounded-2xl border border-[#e3e1e9] p-3"><legend className="px-1 text-xs font-black">{labelText}</legend><label className={label}>Tipo<select className={input} value={current.type} onChange={(event) => onChange({ ...current, type: event.target.value as PresenceAction["type"] })}><option value="start_conversion_goal">Iniciar conversão</option><option value="go_to_presence_page">Ir para página</option><option value="scroll_to_section">Rolar para seção</option><option value="open_url">Abrir URL</option><option value="open_whatsapp">Abrir WhatsApp</option></select></label><label className={`${label} mt-3`}>Texto<input className={input} value={current.label} onChange={(event) => onChange({ ...current, label: event.target.value })} /></label>{current.type === "start_conversion_goal" ? <label className={`${label} mt-3`}>Meta<select className={input} value={current.conversionGoalId || ""} onChange={(event) => onChange({ ...current, conversionGoalId: event.target.value || undefined })}><option value="">Selecione</option>{(project.conversionGoals || []).filter((goal) => goal.isActive).map((goal) => <option key={goal.id} value={goal.id}>{goal.name}</option>)}</select></label> : null}{current.type === "go_to_presence_page" ? <label className={`${label} mt-3`}>Página<select className={input} value={current.pageId || page.id} onChange={(event) => onChange({ ...current, pageId: event.target.value })}>{(project.presence?.pages || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}{current.type === "scroll_to_section" ? <label className={`${label} mt-3`}>Âncora<input className={input} value={current.anchor || ""} onChange={(event) => onChange({ ...current, anchor: event.target.value })} /></label> : null}{current.type === "open_url" ? <label className={`${label} mt-3`}>URL<input className={input} type="url" value={current.url || ""} onChange={(event) => onChange({ ...current, url: event.target.value })} /></label> : null}{current.type === "open_whatsapp" ? <><label className={`${label} mt-3`}>Telefone<input className={input} value={current.whatsappPhone || ""} onChange={(event) => onChange({ ...current, whatsappPhone: event.target.value })} /></label><label className={`${label} mt-3`}>Mensagem<textarea className={`${input} py-2`} value={current.whatsappMessage || ""} onChange={(event) => onChange({ ...current, whatsappMessage: event.target.value })} /></label></> : null}<button type="button" onClick={() => onChange(undefined)} className="mt-3 text-xs font-bold text-[#a43b3b]">Remover ação</button></fieldset>;
}

function HeroEditor(props: EditorProps) { const content = props.section.content as any; return <div className="space-y-3"><label className={label}>Alinhamento<select className={input} value={content.alignment || "left"} onChange={(event) => patchContent(props, { alignment: event.target.value })}><option value="left">À esquerda</option><option value="center">Centralizado</option></select></label><ActionEditor project={props.project} page={props.page} action={content.primaryAction} onChange={(primaryAction) => patchContent(props, { primaryAction })} labelText="Ação principal" /><ActionEditor project={props.project} page={props.page} action={content.secondaryAction} onChange={(secondaryAction) => patchContent(props, { secondaryAction })} labelText="Ação secundária" /></div>; }
function ConversionEditor(props: EditorProps) { const content = props.section.content as any; return <div className="space-y-3"><ActionEditor project={props.project} page={props.page} action={content.primaryAction} onChange={(primaryAction) => primaryAction && patchContent(props, { primaryAction })} labelText="Ação principal" /><ActionEditor project={props.project} page={props.page} action={content.secondaryAction} onChange={(secondaryAction) => patchContent(props, { secondaryAction })} labelText="Ação secundária" /></div>; }
function BodyEditor(props: EditorProps) { const content = props.section.content as any; return <><label className={label}>Conteúdo<textarea className={`${input} min-h-40 py-3`} value={content.body || ""} onChange={(event) => patchContent(props, { body: event.target.value })} /></label><div className="mt-3"><ActionEditor project={props.project} page={props.page} action={content.action} onChange={(action) => patchContent(props, { action })} /></div></>; }
function ItemsEditor(props: EditorProps) { const content = props.section.content as any; const items: any[] = content.items || []; const faq = props.section.type === "faq"; return <div className="space-y-3">{items.map((item, index) => <div key={item.id || index} className="rounded-2xl border border-[#e3e1e9] p-3"><label className={label}>{faq ? "Pergunta" : "Título"}<input className={input} value={faq ? item.question || "" : item.title || item.name || item.value || ""} onChange={(event) => { const next = items.map((candidate, position) => position === index ? { ...candidate, [faq ? "question" : item.name !== undefined ? "name" : item.value !== undefined ? "value" : "title"]: event.target.value } : candidate); patchContent(props, { items: next }); }} /></label><label className={`${label} mt-2`}>{faq ? "Resposta" : "Descrição"}<textarea className={`${input} py-2`} value={faq ? item.answer || "" : item.description || item.quote || item.label || ""} onChange={(event) => { const key = faq ? "answer" : item.quote !== undefined ? "quote" : item.label !== undefined ? "label" : "description"; patchContent(props, { items: items.map((candidate, position) => position === index ? { ...candidate, [key]: event.target.value } : candidate) }); }} /></label><button type="button" aria-label="Excluir item" onClick={() => patchContent(props, { items: items.filter((_, position) => position !== index) })} className="mt-2 inline-flex gap-1 text-xs font-bold text-[#a43b3b]"><Trash2 size={13} />Excluir</button></div>)}<button type="button" onClick={() => patchContent(props, { items: [...items, faq ? { id: crypto.randomUUID(), question: "Nova pergunta", answer: "Escreva a resposta." } : { id: crypto.randomUUID(), title: "Novo item", description: "Descreva este item." }] })} className="inline-flex min-h-9 items-center gap-2 rounded-xl border border-[#dedce7] px-3 text-xs font-bold"><Plus size={14} />Adicionar item</button></div>; }
function CommercialEditor(props: EditorProps) { const content = props.section.content as any; const services = props.section.type === "services"; const options = services ? props.project.commercialConfig?.serviceOfferings || [] : props.project.commercialConfig?.catalogItems || []; const key = services ? "serviceIds" : "itemIds"; const chosen: string[] = content[key] || []; return <div><p className="text-xs leading-5 text-[#77727e]">Os cards usam os dados comerciais existentes. Nada é duplicado nesta seção.</p><div className="mt-3 space-y-2">{options.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-xl border border-[#e3e1e9] p-3 text-sm font-bold"><input type="checkbox" checked={!chosen.length || chosen.includes(item.id)} onChange={(event) => { const base = chosen.length ? chosen : options.map((candidate) => candidate.id); patchContent(props, { [key]: event.target.checked ? [...new Set([...base, item.id])] : base.filter((id) => id !== item.id) }); }} />{item.name}</label>)}</div><label className={`${label} mt-3`}>Layout<select className={input} value={content.layout || "grid"} onChange={(event) => patchContent(props, { layout: event.target.value })}><option value="grid">Grade</option><option value="list">Lista</option><option value="featured">Destaque</option></select></label></div>; }
function MediaEditor(props: EditorProps) {
  const content = props.section.content as any;
  const assets = (props.project.mediaAssets || []).filter((asset) => asset.status !== "failed" && (asset.mimeType.startsWith("image/") || asset.assetType === "image" || asset.assetType === "logo" || asset.assetType === "portfolio"));
  const multi = ["gallery", "portfolio", "logo_cloud"].includes(props.section.type);
  const selected: string[] = multi ? content.assetIds || [] : props.section.type === "hero" ? [content.media?.assetId].filter(Boolean) : props.section.type === "video" ? [content.posterAssetId].filter(Boolean) : [content.mediaAssetId].filter(Boolean);
  function select(assetId: string, checked: boolean) {
    if (multi) return patchContent(props, { assetIds: checked ? [...new Set([...selected, assetId])] : selected.filter((id) => id !== assetId) });
    if (props.section.type === "hero") return patchContent(props, { media: checked ? { ...(content.media || {}), assetId, position: content.media?.position || "right" } : undefined });
    if (props.section.type === "video") return patchContent(props, { posterAssetId: checked ? assetId : undefined });
    patchContent(props, { mediaAssetId: checked ? assetId : undefined });
  }
  return <div><p className="text-xs leading-5 text-[#77727e]">Selecione arquivos da Media Library deste negócio. A seção guarda apenas referências, sem duplicar mídia.</p>{assets.length ? <div className="mt-3 grid gap-2">{assets.map((asset) => <label key={asset.id} className="flex min-h-11 items-center gap-3 rounded-xl border border-[#e3e1e9] p-3 text-xs font-bold"><input type={multi ? "checkbox" : "radio"} name={multi ? undefined : `media-${props.section.id}`} checked={selected.includes(asset.id)} onChange={(event) => select(asset.id, event.target.checked)} /><span className="min-w-0 flex-1 truncate">{asset.originalName}</span><span className="text-[9px] uppercase text-[#8a8691]">{asset.assetType || "imagem"}</span></label>)}</div> : <p className="mt-3 rounded-xl bg-[#f4f3f7] p-3 text-xs text-[#77727e]">Nenhuma imagem pronta na Media Library. Envie arquivos em Mídia e volte para selecionar.</p>}</div>;
}
function SimpleEditor(props: EditorProps) { const content = props.section.content as any; const fields = Object.entries(content).filter(([, value]) => typeof value === "string" || typeof value === "boolean"); return <div className="space-y-3">{fields.map(([key, value]) => typeof value === "boolean" ? <label key={key} className="flex items-center justify-between gap-3 text-xs font-extrabold">{key}<input type="checkbox" checked={Boolean(value)} onChange={(event) => patchContent(props, { [key]: event.target.checked })} /></label> : <label key={key} className={label}>{key}<input className={input} value={String(value)} onChange={(event) => patchContent(props, { [key]: event.target.value })} /></label>)}{!fields.length ? <p className="rounded-xl bg-[#f4f3f7] p-3 text-xs text-[#77727e]">Esta seção usa a biblioteca de mídia ou dados confirmados do projeto.</p> : null}</div>; }

export const sectionEditorRegistry: Record<PresenceSectionType, (props: EditorProps) => React.ReactNode> = {
  hero: HeroEditor, rich_text: BodyEditor, benefits: ItemsEditor, feature_grid: ItemsEditor, services: CommercialEditor, products: CommercialEditor,
  about: BodyEditor, stats: ItemsEditor, logo_cloud: MediaEditor, gallery: MediaEditor, portfolio: MediaEditor, testimonials: ItemsEditor, faq: ItemsEditor,
  pricing: ItemsEditor, locations: SimpleEditor, contact: SimpleEditor, video: SimpleEditor, conversion_cta: ConversionEditor, divider: SimpleEditor,
};

export function SectionInspector(props: EditorProps) {
  const Editor = sectionEditorRegistry[props.section.type];
  return <div className="space-y-4"><div className="grid gap-3"><label className={label}>Sobrancelha<input className={input} value={props.section.eyebrow || ""} onChange={(event) => props.onChange({ ...props.section, eyebrow: event.target.value || undefined })} /></label><label className={label}>Título<input className={input} value={props.section.title || ""} onChange={(event) => props.onChange({ ...props.section, title: event.target.value || undefined })} /></label><label className={label}>Descrição<textarea className={`${input} min-h-24 py-2`} value={props.section.description || ""} onChange={(event) => props.onChange({ ...props.section, description: event.target.value || undefined })} /></label><label className={label}>Âncora<input className={input} value={props.section.anchor || ""} onChange={(event) => props.onChange({ ...props.section, anchor: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "") || undefined })} /></label></div>{["hero", "about"].includes(props.section.type) ? <><div className="h-px bg-[#e8e6ed]" /><MediaEditor {...props} /></> : null}<div className="h-px bg-[#e8e6ed]" />{Editor(props)}<div className="h-px bg-[#e8e6ed]" /><div className="grid grid-cols-2 gap-2"><label className={label}>Fundo<select className={input} value={props.section.style.theme || "default"} onChange={(event) => props.onChange({ ...props.section, style: { ...props.section.style, theme: event.target.value as PresenceSection["style"]["theme"] } })}><option value="default">Padrão</option><option value="muted">Suave</option><option value="brand">Marca</option><option value="dark">Escuro</option></select></label><label className={label}>Espaço<select className={input} value={props.section.style.spacing || "normal"} onChange={(event) => props.onChange({ ...props.section, style: { ...props.section.style, spacing: event.target.value as PresenceSection["style"]["spacing"] } })}><option value="compact">Compacto</option><option value="normal">Normal</option><option value="airy">Amplo</option></select></label></div></div>;
}
