import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { activationCreateSchema, activationPatchSchema } from "@/features/activations/activation.schema";
import { activationOfferDraftSchema } from "@/features/activations/activation-offer.schema";
import { activationPlacementDraftSchema } from "@/features/activations/activation-placement.schema";
import type { ConversionActivation } from "@/features/activations/activation.types";
import { activationKey } from "@/features/activations/activation-utils";
import { ActivationRepository } from "./activation-repository";
import { publishActivationSnapshot } from "./activation-publisher";
export class ActivationService { private readonly repository: ActivationRepository; constructor(database?:SupabaseClient|null){ this.repository=new ActivationRepository(database); }
 async list(projectId:string){return this.repository.list(projectId)} async get(projectId:string,id:string){return this.repository.get(projectId,id)}
 async create(input:{workspaceId:string;projectId:string;actorId?:string;data:unknown}){ const data=activationCreateSchema.parse(input.data); const id=crypto.randomUUID(); const now=new Date().toISOString(); const item:ConversionActivation={ id,workspaceId:input.workspaceId,projectId:input.projectId,activationKey:data.activationKey||activationKey(data.name),name:data.name,description:data.description,activationType:data.activationType,status:data.status||"draft",conversionGoalId:data.conversionGoalId,defaultDestinationId:data.defaultDestinationId,title:data.title,message:data.message,startsAt:data.startsAt,endsAt:data.endsAt,timezone:data.timezone||"America/Sao_Paulo",priority:data.priority||0,requiresIdentity:data.requiresIdentity||false,identityMode:data.identityMode||"phone",identityVerification:data.identityVerification||"none",completionChannel:data.completionChannel,eligibility:data.eligibility||{},limits:data.limits||{},settings:data.settings||{},offers:(data.offers||[]).map((value)=>({ ...activationOfferDraftSchema.parse(value), id:crypto.randomUUID(),activationId:id })),placements:(data.placements||[]).map((value)=>({ ...activationPlacementDraftSchema.parse(value),id:crypto.randomUUID(),activationId:id })),entryPointIds:data.entryPointIds||[],locationIds:data.locationIds||[],publishedSnapshot:data.publishedSnapshot,publishedAt:data.publishedAt,version:data.version||1,createdAt:now,updatedAt:now }; return this.repository.save(item); }
 async patch(projectId:string,id:string,data:unknown){ const current=await this.get(projectId,id); if(!current) return null; const patch=activationPatchSchema.parse(data); return this.repository.save({ ...current,...patch,updatedAt:new Date().toISOString(),offers:patch.offers ? patch.offers.map((value)=>({ ...activationOfferDraftSchema.parse(value),id:crypto.randomUUID(),activationId:id })) : current.offers,placements:patch.placements ? patch.placements.map((value)=>({ ...activationPlacementDraftSchema.parse(value),id:crypto.randomUUID(),activationId:id })) : current.placements } as ConversionActivation); }
 async action(projectId:string,id:string,action:"publish"|"pause"|"resume"|"end"){ const current=await this.get(projectId,id); if(!current) return null; const next=action==="publish"?publishActivationSnapshot(current):{...current,status:action==="pause"?"paused":action==="end"?"ended":(current.startsAt&&new Date(current.startsAt)>new Date()?"scheduled":"active") as ConversionActivation["status"],updatedAt:new Date().toISOString()}; return this.repository.save(next); }
 async duplicate(projectId:string,id:string){const current=await this.get(projectId,id); if(!current)return null; return this.create({workspaceId:current.workspaceId,projectId,data:{...current,name:`${current.name} — cópia`,activationKey:`${current.activationKey}-copia-${Date.now()}`,status:"draft",startsAt:undefined,endsAt:undefined,publishedAt:undefined,publishedSnapshot:undefined,offers:current.offers,placements:current.placements}})}
 async remove(projectId:string,id:string){const current=await this.get(projectId,id); if(!current)return false; if(current.publishedAt){await this.repository.save({...current,status:"archived"});return true;} await this.repository.remove(projectId,id);return true;}
}
