import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ActivationOffer, ActivationPlacement, ConversionActivation } from "@/features/activations/activation.types";
import { activationMemory } from "./activation-memory";
const opt = (value: unknown) => value == null ? undefined : String(value);
function offer(row: Record<string, unknown>): ActivationOffer { return { id: String(row.id), activationId: String(row.activation_id), offerType: row.offer_type as ActivationOffer["offerType"], label: String(row.label), description: opt(row.description), percentage: row.percentage == null ? undefined : Number(row.percentage), amount: row.amount == null ? undefined : Number(row.amount), specialPrice: row.special_price == null ? undefined : Number(row.special_price), currency: String(row.currency), minSubtotal: row.min_subtotal == null ? undefined : Number(row.min_subtotal), maxDiscount: row.max_discount == null ? undefined : Number(row.max_discount), scope: (row.scope || {}) as ActivationOffer["scope"], benefitConfig: (row.benefit_config || {}) as Record<string, unknown>, isActive: Boolean(row.is_active), createdAt: opt(row.created_at), updatedAt: opt(row.updated_at) }; }
function placement(row: Record<string, unknown>): ActivationPlacement { return { id: String(row.id), activationId: String(row.activation_id), presencePageId: opt(row.presence_page_id), presenceSectionId: opt(row.presence_section_id), placementType: row.placement_type as ActivationPlacement["placementType"], content: (row.content || {}) as Record<string, unknown>, style: (row.style || {}) as Record<string, unknown>, priority: Number(row.priority || 0), isActive: Boolean(row.is_active) }; }
function activation(row: Record<string, unknown>): ConversionActivation { const offers = (row.activation_offers || []) as Record<string, unknown>[]; const placements = (row.activation_placements || []) as Record<string, unknown>[]; const entries = (row.activation_entry_points || []) as Array<{ entry_point_id: string }>; const locations = (row.activation_locations || []) as Array<{ location_id: string }>; return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: String(row.project_id), activationKey: String(row.activation_key), name: String(row.name), description: opt(row.description), activationType: row.activation_type as ConversionActivation["activationType"], status: row.status as ConversionActivation["status"], conversionGoalId: opt(row.conversion_goal_id), defaultDestinationId: opt(row.default_destination_id), title: opt(row.title), message: opt(row.message), startsAt: opt(row.starts_at), endsAt: opt(row.ends_at), timezone: String(row.timezone), priority: Number(row.priority || 0), requiresIdentity: Boolean(row.requires_identity), identityMode: row.identity_mode as ConversionActivation["identityMode"], completionChannel: row.completion_channel as ConversionActivation["completionChannel"], eligibility: (row.eligibility || {}) as ConversionActivation["eligibility"], limits: (row.limits || {}) as ConversionActivation["limits"], settings: (row.settings || {}) as ConversionActivation["settings"], offers: offers.map(offer), placements: placements.map(placement), entryPointIds: entries.map((item) => item.entry_point_id), locationIds: locations.map((item) => item.location_id), publishedSnapshot: row.published_snapshot as Record<string, unknown> | undefined, publishedAt: opt(row.published_at), version: Number(row.version || 1), createdAt: opt(row.created_at), updatedAt: opt(row.updated_at) }; }
const select = "*,activation_offers(*),activation_placements(*),activation_entry_points(entry_point_id),activation_locations(location_id)";
export class ActivationRepository { constructor(private readonly database?: SupabaseClient | null) {}
  async list(projectId: string) { if (!this.database) return [...activationMemory.values()].filter((item) => item.projectId === projectId).toSorted((a,b) => (b.createdAt || "").localeCompare(a.createdAt || "")); const { data,error } = await this.database.from("conversion_activations").select(select).eq("project_id",projectId).order("created_at",{ascending:false}); if(error) throw error; return (data || []).map((row) => activation(row)); }
  async get(projectId: string,id: string) { if (!this.database) { const item=activationMemory.get(id); return item?.projectId === projectId ? item : null; } const {data,error}=await this.database.from("conversion_activations").select(select).eq("project_id",projectId).eq("id",id).maybeSingle(); if(error) throw error; return data ? activation(data) : null; }
  async save(item: ConversionActivation) { if (!this.database) { activationMemory.set(item.id,item); return item; } const payload={ id:item.id,workspace_id:item.workspaceId,project_id:item.projectId,activation_key:item.activationKey,name:item.name,description:item.description||null,activation_type:item.activationType,status:item.status,conversion_goal_id:item.conversionGoalId||null,default_destination_id:item.defaultDestinationId||null,title:item.title||null,message:item.message||null,starts_at:item.startsAt||null,ends_at:item.endsAt||null,timezone:item.timezone,priority:item.priority,requires_identity:item.requiresIdentity,identity_mode:item.identityMode,completion_channel:item.completionChannel||null,eligibility:item.eligibility,limits:item.limits,settings:item.settings,published_snapshot:item.publishedSnapshot||null,published_at:item.publishedAt||null,version:item.version }; const {error}=await this.database.from("conversion_activations").upsert(payload); if(error) throw error; await Promise.all([this.database.from("activation_offers").delete().eq("activation_id",item.id),this.database.from("activation_placements").delete().eq("activation_id",item.id),this.database.from("activation_entry_points").delete().eq("activation_id",item.id),this.database.from("activation_locations").delete().eq("activation_id",item.id)]); if(item.offers.length) { const {error:offerError}=await this.database.from("activation_offers").insert(item.offers.map((value)=>({id:value.id,activation_id:item.id,offer_type:value.offerType,label:value.label,description:value.description||null,percentage:value.percentage??null,amount:value.amount??null,special_price:value.specialPrice??null,currency:value.currency,min_subtotal:value.minSubtotal??null,max_discount:value.maxDiscount??null,scope:value.scope,benefit_config:value.benefitConfig,is_active:value.isActive}))); if(offerError) throw offerError; } if(item.placements.length) { const {error:placementError}=await this.database.from("activation_placements").insert(item.placements.map((value)=>({id:value.id,activation_id:item.id,presence_page_id:value.presencePageId||null,presence_section_id:value.presenceSectionId||null,placement_type:value.placementType,content:value.content,style:value.style,priority:value.priority,is_active:value.isActive}))); if(placementError) throw placementError; } if(item.entryPointIds?.length) await this.database.from("activation_entry_points").insert(item.entryPointIds.map((entry_point_id)=>({activation_id:item.id,entry_point_id}))); if(item.locationIds?.length) await this.database.from("activation_locations").insert(item.locationIds.map((location_id)=>({activation_id:item.id,location_id}))); return (await this.get(item.projectId,item.id))!; }
  async remove(projectId:string,id:string){ if(!this.database){ activationMemory.delete(id); return; } const {error}=await this.database.from("conversion_activations").delete().eq("project_id",projectId).eq("id",id); if(error) throw error; }
}
