"use client";

import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Select } from "@/components/ui/field";
import type { FormField } from "@/types";

export function QuoteQuestionBuilder({ questions, onChange }: { questions: FormField[]; onChange: (questions: FormField[]) => void }) {
  function update(id: string, patch: Partial<FormField>) { onChange(questions.map((question) => question.id === id ? { ...question, ...patch } : question)); }
  return <div><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-extrabold">Perguntas</h3><p className="text-xs text-[#777781]">Dados usados nas regras e no atendimento.</p></div><Button size="sm" variant="secondary" onClick={() => onChange([...questions, { id: crypto.randomUUID(), key: `campo_${questions.length + 1}`, label: "Nova pergunta", type: "text", required: false }])}><Plus data-icon="inline-start" />Adicionar</Button></div><div className="flex flex-col gap-3">{questions.map((question, index) => <div key={question.id} className="grid gap-3 rounded-[16px] border border-[#e3e2e9] p-4 sm:grid-cols-[1fr_180px_auto]"><div><Label htmlFor={`question-label-${question.id}`}>Pergunta {index + 1}</Label><Input id={`question-label-${question.id}`} value={question.label} onChange={(event) => update(question.id, { label: event.target.value })} /></div><div><Label htmlFor={`question-type-${question.id}`}>Tipo</Label><Select id={`question-type-${question.id}`} value={question.type} onChange={(event) => update(question.id, { type: event.target.value as FormField["type"] })}><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista</option><option value="radio">Escolha única</option><option value="checkbox">Múltipla escolha</option><option value="file">Foto/arquivo</option></Select></div><Button size="icon" variant="ghost" className="self-end" aria-label={`Excluir pergunta ${index + 1}`} onClick={() => onChange(questions.filter((item) => item.id !== question.id))}><Trash2 /></Button><div className="sm:col-span-3"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={question.required} onChange={(event) => update(question.id, { required: event.target.checked })} />Obrigatória</label>{question.type === "select" || question.type === "radio" || question.type === "checkbox" ? <Input className="mt-3" value={(question.options || []).join(", ")} onChange={(event) => update(question.id, { options: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} placeholder="Opções separadas por vírgula" /> : null}</div></div>)}</div></div>;
}
