"use client";

import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Select } from "@/components/ui/field";
import type { FormField, QuoteCalculationRule } from "@/types";

export function QuoteRuleBuilder({ rules, questions, onChange }: { rules: QuoteCalculationRule[]; questions: FormField[]; onChange: (rules: QuoteCalculationRule[]) => void }) {
  const update = (id: string, patch: Partial<QuoteCalculationRule>) => onChange(rules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule));
  return <div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-extrabold">Regras de cálculo</h3><Button size="sm" variant="secondary" onClick={() => onChange([...rules, { id: crypto.randomUUID(), condition: { field: questions[0]?.key || "", operator: "equals", value: "" }, operation: "add", amount: 0 }])}><Plus data-icon="inline-start" />Regra</Button></div><div className="flex flex-col gap-3">{rules.map((rule) => <div key={rule.id} className="grid gap-3 rounded-[16px] border border-[#e3e2e9] p-4 sm:grid-cols-4"><div><Label>Campo</Label><Select value={rule.condition.field} onChange={(event) => update(rule.id, { condition: { ...rule.condition, field: event.target.value } })}><option value="">Selecione</option>{questions.map((question) => <option key={question.id} value={question.key}>{question.label}</option>)}</Select></div><div><Label>Condição</Label><Select value={rule.condition.operator} onChange={(event) => update(rule.id, { condition: { ...rule.condition, operator: event.target.value as typeof rule.condition.operator } })}><option value="equals">Igual</option><option value="contains">Contém</option><option value="greater_than">Maior que</option><option value="less_than">Menor que</option></Select></div><div><Label>Valor esperado</Label><Input value={String(rule.condition.value)} onChange={(event) => update(rule.id, { condition: { ...rule.condition, value: event.target.value } })} /></div><div><Label>Operação</Label><div className="flex gap-2"><Select value={rule.operation} onChange={(event) => update(rule.id, { operation: event.target.value as QuoteCalculationRule["operation"] })}><option value="add">Somar</option><option value="multiply">Multiplicar</option><option value="set">Definir</option><option value="range">Faixa</option></Select><Button size="icon" variant="ghost" aria-label="Excluir regra" onClick={() => onChange(rules.filter((item) => item.id !== rule.id))}><Trash2 /></Button></div></div><div className="sm:col-span-2"><Label>Valor</Label><Input type="number" step="0.01" value={rule.amount ?? ""} onChange={(event) => update(rule.id, { amount: event.target.value ? Number(event.target.value) : undefined })} /></div>{rule.operation === "range" ? <><div><Label>Mínimo</Label><Input type="number" value={rule.minAmount ?? ""} onChange={(event) => update(rule.id, { minAmount: event.target.value ? Number(event.target.value) : undefined })} /></div><div><Label>Máximo</Label><Input type="number" value={rule.maxAmount ?? ""} onChange={(event) => update(rule.id, { maxAmount: event.target.value ? Number(event.target.value) : undefined })} /></div></> : null}</div>)}</div></div>;
}
