"use client";
import { MapPin, Plus } from "lucide-react";
import { useState } from "react";
import { LocationForm } from "@/components/commercial-data/locations/location-form";
import { LocationRoutingTest } from "@/components/commercial-data/locations/location-routing-test";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { BusinessLocation, Project, RoutingDestination } from "@/types";
type Patch = Partial<NonNullable<Project["commercialConfig"]>>;
export function LocationsPanel({ projectId, locations, destinations, onChange }: { projectId: string; locations: BusinessLocation[]; destinations: RoutingDestination[]; onChange: (value: Patch) => void }) { const [editing, setEditing] = useState<BusinessLocation | null>(null); const add = () => setEditing({ id: crypto.randomUUID(), projectId, name: "", countryCode: "BR", geocodingStatus: "pending", timezone: "America/Sao_Paulo", openingHours: [], supportsDelivery: false, supportsPickup: false, supportsInPerson: true, priority: 0, isActive: true }); const save = () => { if (!editing?.name.trim()) return; onChange({ locations: locations.some((item) => item.id === editing.id) ? locations.map((item) => item.id === editing.id ? editing : item) : [...locations, editing] }); setEditing(null); }; return <section className="flex flex-col gap-8"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-extrabold">Unidades e roteamento</h2><p className="mt-1 text-sm text-[#74747e]">Endereços, coordenadas, horários, raios e destino correto.</p></div><Button onClick={add}><Plus data-icon="inline-start" />Nova unidade</Button></div><div className="grid gap-3 sm:grid-cols-2">{locations.map((location) => <button type="button" key={location.id} onClick={() => setEditing(location)} className="focus-ring flex items-start gap-3 rounded-[18px] border border-[#e5e4eb] p-4 text-left hover:border-[#0186fc]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#f7fbff] text-[#0054fc]"><MapPin size={18} /></span><span><strong className="block">{location.name}</strong><small className="mt-1 block text-[#777781]">{[location.neighborhood, location.city, location.state].filter(Boolean).join(" · ") || "Endereço pendente"}</small><small className="mt-1 block font-semibold text-[#0054fc]">{location.geocodingStatus}</small></span></button>)}</div><LocationRoutingTest locations={locations} /><Dialog open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null); }}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Unidade de atendimento</DialogTitle></DialogHeader>{editing ? <LocationForm value={editing} destinations={destinations} onChange={setEditing} /> : null}<DialogFooter><Button variant="danger" disabled={!editing || !locations.some((item) => item.id === editing.id)} onClick={() => { if (editing) onChange({ locations: locations.filter((item) => item.id !== editing.id) }); setEditing(null); }}>Excluir</Button><Button onClick={save}>Salvar unidade</Button></DialogFooter></DialogContent></Dialog></section>; }
