"use client";
import { Plus, Trash2 } from "lucide-react";
import { AvailabilityExceptions } from "@/components/commercial-data/scheduling/availability-exceptions";
import { AvailabilityWeek } from "@/components/commercial-data/scheduling/availability-week";
import { ResourceForm } from "@/components/commercial-data/scheduling/resource-form";
import { SchedulableServiceForm } from "@/components/commercial-data/scheduling/schedulable-service-form";
import { SchedulingPreview } from "@/components/commercial-data/scheduling/scheduling-preview";
import { Button } from "@/components/ui/button";
import type { AvailabilityException, AvailabilityRule, Project, SchedulableResource, SchedulableService, ServiceOffering } from "@/types";
type ConfigPatch = Partial<NonNullable<Project["commercialConfig"]>>;
export function SchedulingPanel({ projectId, services, serviceOfferings, resources, availabilityRules, exceptions, onChange }: { projectId: string; services: SchedulableService[]; serviceOfferings: ServiceOffering[]; resources: SchedulableResource[]; availabilityRules: AvailabilityRule[]; exceptions: AvailabilityException[]; onChange: (value: ConfigPatch) => void }) { const addService = () => onChange({ schedulableServices: [...services, { id: crypto.randomUUID(), projectId, name: "", durationMinutes: 60, bufferBeforeMinutes: 0, bufferAfterMinutes: 0, capacity: 1, confirmationMode: "manual_approval", isActive: true }] }); const addResource = () => onChange({ resources: [...resources, { id: crypto.randomUUID(), projectId, name: "", kind: "professional", isActive: true }] }); return <section className="flex flex-col gap-8"><div><h2 className="text-lg font-extrabold">Agenda</h2><p className="mt-1 text-sm text-[#74747e]">Serviços, recursos, horários, intervalos e bloqueios.</p></div><SchedulingPreview services={services} rules={availabilityRules} /><section><div className="mb-3 flex justify-between"><h3 className="font-extrabold">Serviços agendáveis</h3><Button size="sm" variant="secondary" onClick={addService}><Plus data-icon="inline-start" />Serviço</Button></div><div className="flex flex-col gap-3">{services.map((service) => <div key={service.id} className="relative"><SchedulableServiceForm value={service} serviceOfferings={serviceOfferings} onChange={(next) => onChange({ schedulableServices: services.map((item) => item.id === next.id ? next : item) })} /><Button aria-label="Excluir serviço" size="icon" variant="ghost" className="absolute right-2 top-2" onClick={() => onChange({ schedulableServices: services.filter((item) => item.id !== service.id) })}><Trash2 size={15} /></Button></div>)}</div></section><section><div className="mb-3 flex justify-between"><h3 className="font-extrabold">Profissionais, salas e equipamentos</h3><Button size="sm" variant="secondary" onClick={addResource}><Plus data-icon="inline-start" />Recurso</Button></div><div className="flex flex-col gap-3">{resources.map((resource) => <div key={resource.id} className="relative"><ResourceForm value={resource} onChange={(next) => onChange({ resources: resources.map((item) => item.id === next.id ? next : item) })} /><Button aria-label="Excluir recurso" size="icon" variant="ghost" className="absolute right-2 top-2" onClick={() => onChange({ resources: resources.filter((item) => item.id !== resource.id) })}><Trash2 size={15} /></Button></div>)}</div></section><AvailabilityWeek projectId={projectId} rules={availabilityRules} onChange={(value) => onChange({ availabilityRules: value })} /><AvailabilityExceptions projectId={projectId} exceptions={exceptions} onChange={(value) => onChange({ availabilityExceptions: value })} /></section>; }
