"use client";
import { Input, Label, Select } from "@/components/ui/field";
import { Switch } from "@/components/ui/switch";
import type { SchedulableService, ServiceOffering } from "@/types";

export function SchedulableServiceForm({ value, serviceOfferings, onChange }: { value: SchedulableService; serviceOfferings: ServiceOffering[]; onChange: (value: SchedulableService) => void }) {
  const patch = (next: Partial<SchedulableService>) => onChange({ ...value, ...next });
  const offering = serviceOfferings.find((item) => item.id === value.serviceOfferingId);
  return <div className="grid gap-4 rounded-[18px] border border-[#e5e4eb] p-4 sm:grid-cols-3"><div className="sm:col-span-2"><Label htmlFor={`schedule-name-${value.id}`}>Serviço</Label><Input id={`schedule-name-${value.id}`} value={value.name} onChange={(event) => patch({ name: event.target.value })} /></div><div><Label htmlFor={`schedule-offering-${value.id}`}>Oferta e preço</Label><Select id={`schedule-offering-${value.id}`} value={value.serviceOfferingId || ""} onChange={(event) => patch({ serviceOfferingId: event.target.value || undefined })}><option value="">Sem oferta associada</option>{serviceOfferings.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>{offering ? <p className="mt-1 text-[11px] text-[#777781]">Preço vem de Serviços: {offering.priceMode === "on_request" ? "sob consulta" : offering.price != null ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: offering.currency }).format(offering.price) : offering.priceMode}</p> : null}</div><div><Label htmlFor={`schedule-duration-${value.id}`}>Duração (min)</Label><Input id={`schedule-duration-${value.id}`} type="number" min="1" value={value.durationMinutes} onChange={(event) => patch({ durationMinutes: Number(event.target.value) })} /></div><div><Label htmlFor={`schedule-before-${value.id}`}>Buffer antes</Label><Input id={`schedule-before-${value.id}`} type="number" min="0" value={value.bufferBeforeMinutes} onChange={(event) => patch({ bufferBeforeMinutes: Number(event.target.value) })} /></div><div><Label htmlFor={`schedule-after-${value.id}`}>Buffer depois</Label><Input id={`schedule-after-${value.id}`} type="number" min="0" value={value.bufferAfterMinutes} onChange={(event) => patch({ bufferAfterMinutes: Number(event.target.value) })} /></div><div><Label htmlFor={`schedule-capacity-${value.id}`}>Capacidade</Label><Input id={`schedule-capacity-${value.id}`} type="number" min="1" value={value.capacity} onChange={(event) => patch({ capacity: Number(event.target.value) })} /></div><div><Label htmlFor={`schedule-confirm-${value.id}`}>Confirmação</Label><Select id={`schedule-confirm-${value.id}`} value={value.confirmationMode} onChange={(event) => patch({ confirmationMode: event.target.value as SchedulableService["confirmationMode"] })}><option value="instant">Imediata</option><option value="manual_approval">Aprovação manual</option><option value="external_system">Sistema externo</option></Select></div><label className="flex items-center gap-3 self-end pb-3 text-sm font-semibold"><Switch checked={value.isActive} onCheckedChange={(isActive) => patch({ isActive })} />Ativo</label></div>;
}
