import "server-only";
import { createServiceClient } from "@/lib/supabase/server";
import type { Notification, NotificationPreference } from "@/types";
function database() { const client = createServiceClient(); if (!client) throw new Error("Supabase não configurado para notificações."); return client; }
function fromRow(row: Record<string, unknown>): Notification { return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: row.project_id ? String(row.project_id) : undefined, userId: row.user_id ? String(row.user_id) : undefined, type: String(row.event_key), title: String(row.title), body: String(row.body), actionUrl: row.action_url ? String(row.action_url) : undefined, readAt: row.read_at ? String(row.read_at) : undefined, metadata: (row.metadata || {}) as Record<string, unknown>, createdAt: String(row.created_at) }; }
export const notificationRepository = {
  async workspaceRecipients(workspaceId: string, requested?: string[]) { let query = database().from("workspace_members").select("user_id").eq("workspace_id", workspaceId); if (requested?.length) query = query.in("user_id", requested); const { data, error } = await query; if (error) throw new Error("Não foi possível resolver destinatários."); return (data || []).map((item) => item.user_id); },
  async preference(workspaceId: string, userId: string, eventKey: string) { const { data } = await database().from("notification_preferences").select("*").eq("workspace_id", workspaceId).eq("user_id", userId).eq("event_key", eventKey).maybeSingle(); return data ? { id: data.id, workspaceId: data.workspace_id, userId: data.user_id, eventKey: data.event_key, inApp: data.in_app, email: data.email } as NotificationPreference : { id: "default", workspaceId, userId, eventKey, inApp: true, email: true } as NotificationPreference; },
  async create(input: { workspaceId: string; projectId: string; userId: string; eventKey: string; title: string; body: string; actionUrl?: string; objectType: string; objectId: string; metadata: Record<string, unknown>; readAt?: string }) { const client = database(); const row = { workspace_id: input.workspaceId, project_id: input.projectId, user_id: input.userId, event_key: input.eventKey, title: input.title, body: input.body, action_url: input.actionUrl || null, object_type: input.objectType, object_id: input.objectId, metadata: { ...input.metadata, objectId: input.objectId }, read_at: input.readAt || null }; const { data, error } = await client.from("notifications").insert(row).select("*").single(); if (!error) return fromRow(data); if (error.code !== "23505") throw new Error("Não foi possível criar a notificação."); const { data: existing } = await client.from("notifications").select("*").eq("workspace_id", input.workspaceId).eq("event_key", input.eventKey).eq("object_type", input.objectType).eq("object_id", input.objectId).eq("user_id", input.userId).single(); return fromRow(existing); },
  async delivery(notificationId: string, channel: "in_app" | "email", input: { status: "pending" | "sent" | "failed" | "skipped"; provider?: string; messageId?: string; error?: string }) { await database().from("notification_deliveries").upsert({ notification_id: notificationId, channel, status: input.status, provider: input.provider || null, provider_message_id: input.messageId || null, attempts: 1, last_error: input.error?.slice(0, 300) || null, sent_at: input.status === "sent" ? new Date().toISOString() : null }, { onConflict: "notification_id,channel" }); },
  async userEmail(userId: string) { const { data } = await database().auth.admin.getUserById(userId); return data.user?.email; },
  async list(workspaceId: string, userId: string, filter: "all" | "unread" = "all") { let query = database().from("notifications").select("*").eq("workspace_id", workspaceId).or(`user_id.eq.${userId},user_id.is.null`).order("created_at", { ascending: false }).limit(100); if (filter === "unread") query = query.is("read_at", null); const { data, error } = await query; if (error) throw new Error("Não foi possível carregar notificações."); return (data || []).map(fromRow); },
  async markRead(workspaceId: string, userId: string, ids?: string[]) { let query = database().from("notifications").update({ read_at: new Date().toISOString() }).eq("workspace_id", workspaceId).or(`user_id.eq.${userId},user_id.is.null`).is("read_at", null); if (ids?.length) query = query.in("id", ids); const { error } = await query; if (error) throw new Error("Não foi possível marcar as notificações."); },
  async preferences(workspaceId: string, userId: string) { const { data, error } = await database().from("notification_preferences").select("*").eq("workspace_id", workspaceId).eq("user_id", userId); if (error) throw new Error("Não foi possível carregar as preferências."); return (data || []).map((row) => ({ id: row.id, workspaceId: row.workspace_id, userId: row.user_id, eventKey: row.event_key, inApp: row.in_app, email: row.email } satisfies NotificationPreference)); },
  async savePreferences(workspaceId: string, userId: string, values: Array<{ eventKey: string; inApp: boolean; email: boolean }>) { const { error } = await database().from("notification_preferences").upsert(values.map((item) => ({ workspace_id: workspaceId, user_id: userId, event_key: item.eventKey, in_app: item.inApp, email: item.email })), { onConflict: "workspace_id,user_id,event_key" }); if (error) throw new Error("Não foi possível salvar as preferências."); return this.preferences(workspaceId, userId); },
};
