"use client";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Clock3, Search, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { ConversionDialog } from "./conversion-dialog";
import { OpportunityCard } from "./opportunity-card";
import { OpportunityDetails } from "./opportunity-details";
import { OpportunityFilters } from "./opportunity-filters";
import { backfillConversionGoals } from "@/features/conversion-goals/utils";
import { localStore } from "@/lib/local-store";
import { projectRepository } from "@/lib/repositories/project-repository";
import { isSupabaseConfigured } from "@/lib/supabase/client";
import { transitionOpportunity } from "@/server/opportunities/status";
import type { CommercialOpportunity, OpportunityStatus, Project } from "@/types";

function rowToOpportunity(row: Record<string, unknown>): CommercialOpportunity { return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: String(row.project_id), sessionId: row.session_id ? String(row.session_id) : undefined, conversionGoalId: row.conversion_goal_id ? String(row.conversion_goal_id) : undefined, entryPointId: row.entry_point_id ? String(row.entry_point_id) : undefined, destinationId: row.destination_id ? String(row.destination_id) : undefined, sourceType: row.source_type as CommercialOpportunity["sourceType"], sourceId: String(row.source_id), status: row.status as OpportunityStatus, title: String(row.title), contactName: row.contact_name ? String(row.contact_name) : undefined, contactEmail: row.contact_email ? String(row.contact_email) : undefined, contactPhone: row.contact_phone ? String(row.contact_phone) : undefined, summary: row.summary ? String(row.summary) : undefined, estimatedValue: row.estimated_value == null ? undefined : Number(row.estimated_value), confirmedValue: row.confirmed_value == null ? undefined : Number(row.confirmed_value), currency: String(row.currency || "BRL"), attribution: row.attribution as CommercialOpportunity["attribution"], metadata: row.metadata as Record<string, unknown> || {}, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
export function OpportunitiesPage({ projectId }: { projectId: string }) {
  const [project, setProject] = useState<Project | null>(); const [items, setItems] = useState<CommercialOpportunity[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [filter, setFilter] = useState<"all" | OpportunityStatus>("all"); const [query, setQuery] = useState(""); const [conversionOpen, setConversionOpen] = useState(false);
  useEffect(() => { void projectRepository.getProject(projectId).then((found) => { setProject(found || null); if (!found) return; if (!isSupabaseConfigured()) { const local = localStore.getOpportunities(projectId); setItems(local); setSelectedId(local[0]?.id); return; } void fetch(`/api/projects/${projectId}/opportunities`).then((response) => response.json()).then((payload: { data?: Record<string, unknown>[] }) => { const remote = (payload.data || []).map(rowToOpportunity); setItems(remote); setSelectedId(remote[0]?.id); }); }).catch(() => setProject(null)); }, [projectId]);
  const filtered = useMemo(() => items.filter((item) => (filter === "all" || item.status === filter) && `${item.title} ${item.contactName || ""}`.toLowerCase().includes(query.toLowerCase())), [filter, items, query]); const selected = items.find((item) => item.id === selectedId); const goals = project ? backfillConversionGoals(project) : [];
  if (project === undefined) return <div className="h-80 animate-pulse rounded-[24px] bg-white" />; if (!project) return <div className="rounded-[24px] bg-white p-10 text-center">Negócio não encontrado.</div>;
  async function update(status: OpportunityStatus, input: { confirmedValue?: number; lossReason?: string } = {}) { if (!selected) return; const updated = transitionOpportunity(selected, status, input); setItems((current) => current.map((item) => item.id === selected.id ? updated : item)); if (!isSupabaseConfigured()) { localStore.updateOpportunity(selected.id, updated); if (status === "converted" || status === "lost") localStore.track({ projectId: project!.id, visitorId: "operator", sessionId: selected.sessionId || selected.id, eventName: status === "converted" ? "conversion_confirmed" : "conversion_lost", conversionGoalId: selected.conversionGoalId, entryPointId: selected.entryPointId, destinationId: selected.destinationId, metadata: input }); } else await fetch(`/api/projects/${project!.id}/opportunities`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: selected.id, status, ...input }) }); }
  const counts = { new: items.filter((item) => item.status === "new").length, progress: items.filter((item) => item.status === "in_progress").length, converted: items.filter((item) => item.status === "converted").length };
  return <div className="animate-enter"><header><Link href={`/app/projects/${project.id}`} className="inline-flex items-center gap-2 text-xs font-bold text-[#74727d]"><ArrowLeft size={14} /> {project.name}</Link><div className="mt-4 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-[15px] bg-[#eaf3ff] text-[#0054fc]"><BriefcaseBusiness /></span><div><h1 className="text-3xl font-extrabold tracking-[-.045em]">Oportunidades</h1><p className="mt-1 text-sm text-[#74727d]">Acompanhe cada intenção que virou ação comercial.</p></div></div></header>
  <div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Novas", counts.new, BriefcaseBusiness], ["Em andamento", counts.progress, Clock3], ["Convertidas", counts.converted, CheckCircle2]].map(([label, value, Icon]) => { const StatIcon = Icon as typeof BriefcaseBusiness; return <div key={String(label)} className="rounded-[18px] border border-[#e3e1e8] bg-white p-4"><StatIcon size={17} className="text-[#0054fc]" /><strong className="mt-5 block text-2xl">{Number(value)}</strong><span className="text-xs text-[#77747f]">{String(label)}</span></div>; })}</div>
  <section className="mt-5 grid gap-5 xl:grid-cols-[.76fr_1.24fr]"><div><div className="flex flex-wrap gap-2"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3.5" size={15} /><input aria-label="Buscar oportunidades" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar contato ou oportunidade" className="min-h-11 w-full rounded-xl border border-[#dedce5] bg-white pl-9 pr-3 text-xs" /></label><OpportunityFilters value={filter} onChange={setFilter} /></div><div className="mt-3 grid gap-3">{filtered.length ? filtered.map((item) => <OpportunityCard key={item.id} opportunity={item} onSelect={() => setSelectedId(item.id)} />) : <div className="rounded-[20px] border border-dashed border-[#d9d6e1] p-10 text-center"><strong>Nenhuma oportunidade neste filtro</strong><p className="mt-2 text-xs text-[#77747f]">Novas oportunidades aparecem após uma ação comercial real.</p></div>}</div></div>
  <aside className="rounded-[24px] border border-[#e2e0e8] bg-white p-5 sm:p-6">{selected ? <><OpportunityDetails opportunity={{ ...selected, projectName: project.name }} goal={goals.find((goal) => goal.id === selected.conversionGoalId)} entry={project.entryPoints?.find((entry) => entry.id === selected.entryPointId)} /><div className="mt-7 flex flex-wrap gap-2">{selected.status === "new" ? <Button variant="secondary" onClick={() => void update("in_progress")}>Iniciar atendimento</Button> : null}{!["converted", "archived"].includes(selected.status) ? <Button onClick={() => setConversionOpen(true)}><CheckCircle2 /> Confirmar conversão</Button> : null}{!["lost", "converted", "archived"].includes(selected.status) ? <Button variant="ghost" onClick={() => { const reason = window.prompt("Por que esta oportunidade foi perdida?"); if (reason) void update("lost", { lossReason: reason }); }}><XCircle /> Marcar perdida</Button> : null}</div><ConversionDialog open={conversionOpen} onOpenChange={setConversionOpen} onConfirm={(value) => { void update("converted", { confirmedValue: value }); setConversionOpen(false); }} /></> : <div className="grid min-h-64 place-items-center text-center text-sm text-[#77747f]">Selecione uma oportunidade para ver o contexto.</div>}</aside></section></div>;
}
