import Link from "next/link";
import { ArrowRight, Check, CircleDot, FileText, Images, Link2, MapPin, MessageSquareText as MessageSquareTextIcon, MousePointerClick as MousePointerClickIcon, Package, Route as RouteIcon, ScanLine, Sparkles, Target as TargetIcon } from "lucide-react";
import { MarketingFooter, MarketingHeader } from "@/components/marketing/header";
import { ConversionDemo } from "@/components/marketing/conversion-demo";

const MessageSquareText = MessageSquareTextIcon as typeof MessageSquareTextIcon & string;
const MousePointerClick = MousePointerClickIcon as typeof MousePointerClickIcon & string;
const Route = RouteIcon as typeof RouteIcon & string;
const Target = TargetIcon as typeof TargetIcon & string;

const presenceItems = [["Oferta", Sparkles], ["Serviços", Route], ["Produtos", Package], ["Prova", Check], ["Localização", MapPin], ["FAQ", MessageSquareText], ["Mídia", Images], ["CTA", MousePointerClick]] as const;

export default function HomePage() {
  return <main className="overflow-hidden bg-[#f7f8fa] text-[#07172f]"><MarketingHeader />
    <section className="relative pb-24 pt-36 sm:pt-44"><div className="pointer-events-none absolute inset-0 marketing-grid opacity-40" /><div className="sobe-gradient pointer-events-none absolute -right-48 top-12 size-[34rem] rounded-full opacity-[.14] blur-3xl" /><div className="container-shell relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="max-w-[720px]"><div className="inline-flex items-center gap-2 rounded-full border border-[#b9d4ff] bg-white px-3 py-2 text-xs font-bold text-[#0054fc]"><ScanLine size={14} /> Presença + conversão para tráfego social</div><h1 className="text-balance mt-7 text-[clamp(3.2rem,6.5vw,5.8rem)] font-extrabold leading-[.93] tracking-[-.065em]">Transforme quem chega das suas redes em cliente.</h1><p className="text-balance mt-7 max-w-[680px] text-lg leading-8 text-[#536178] sm:text-xl">Crie uma presença digital que apresenta seu negócio, entende a intenção de cada visitante e o conduz até pedido, orçamento, agendamento, reserva ou atendimento.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/app/onboarding" className="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-[#0054fc] px-6 font-bold text-white shadow-[0_16px_38px_rgba(0,84,252,.22)] transition hover:bg-[#0048d9]">Criar minha Sobe <ArrowRight size={18} /></Link><a href="#como-funciona" className="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-[#d7e1ec] bg-white px-6 font-bold transition hover:border-[#9fc3ff] hover:bg-[#f7fbff]">Ver como funciona <MousePointerClick size={18} /></a></div></div><ConversionDemo /></div></section>

    <section className="bg-[#07172f] py-24 text-white sm:py-30"><div className="container-shell"><div className="max-w-4xl"><span className="text-xs font-bold uppercase tracking-[.16em] text-[#02e5cd]">Presença que trabalha</span><h2 className="text-balance mt-5 text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">Tudo o que seu cliente precisa ver. E o próximo passo que ele precisa tomar.</h2></div><div className="mt-14 grid grid-cols-2 gap-px overflow-hidden rounded-[28px] border border-white/10 bg-white/10 md:grid-cols-4">{presenceItems.map(([item, Icon], index) => <div key={item} className="bg-[#07172f] p-5 sm:p-7"><span className={`grid size-10 place-items-center rounded-xl ${index % 3 === 0 ? "bg-[#02e5cd] text-[#07172f]" : "bg-[#0b2d55] text-[#01d2df]"}`}><Icon size={18} /></span><strong className="mt-7 block text-sm">{item}</strong></div>)}</div></div></section>

    <section id="como-funciona" className="py-24 sm:py-32"><div className="container-shell grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#0054fc]">Conteúdo → ação</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">Cada CTA pode virar uma jornada.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#6d6974]">A página apresenta. O CTA preserva contexto. A jornada faz somente as perguntas necessárias e conduz a intenção ao destino certo.</p></div><div className="rounded-[30px] border border-[#dfdce5] bg-white p-6 shadow-[0_28px_70px_rgba(36,31,66,.08)] sm:p-9"><div className="grid gap-3">{[["Solicitar orçamento", "CTA", MousePointerClick], ["3 perguntas", "Contexto", MessageSquareText], ["Oportunidade qualificada", "Intenção", Target], ["Vendedor certo", "Destino", Route]].map(([title, note, Icon], index) => { const FlowIcon = Icon as typeof Target; return <div key={String(title)}><div className={`flex items-center gap-4 rounded-[18px] border p-4 ${index === 0 ? "border-[#0186fc] bg-[#eaf3ff]" : "border-[#e4e1e8]"}`}><span className="grid size-9 place-items-center rounded-xl bg-[#07172f] text-white"><FlowIcon size={16} /></span><div><strong className="block text-sm">{title}</strong><small className="text-[#7a7681]">{note}</small></div></div>{index < 3 ? <div className="ml-8 h-5 border-l border-dashed border-[#aaa4b9]" /> : null}</div>; })}</div></div></div></section>

    <section className="border-y border-[#e2dfe5] bg-white py-24 sm:py-32"><div className="container-shell"><div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-[.16em] text-[#0054fc]">Site vs. Sobe</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">O atendimento não precisa começar do zero.</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] border border-[#e3e0e6] p-7"><span className="text-xs font-black uppercase tracking-[.14em] text-[#827e89]">Tradicional</span><div className="mt-8 space-y-3">{["Site", "CTA", "WhatsApp genérico", "atendimento começa do zero"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-bold text-[#706c76]"><CircleDot size={14} />{item}</div>)}</div></div><div className="rounded-[28px] bg-[#e9fffc] p-7"><span className="text-xs font-black uppercase tracking-[.14em] text-[#0054fc]">Sobe</span><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Site", "CTA", "contexto", "jornada", "destino certo", "oportunidade organizada"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-white/70 p-3 text-sm font-bold"><Check className="text-[#0054fc]" size={15} />{item}</div>)}</div></div></div></div></section>

    <section className="py-24 sm:py-32"><div className="container-shell grid gap-14 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#0054fc]">Campanhas conectadas</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Crie páginas para campanhas sem perder sua estrutura de conversão.</h2><p className="mt-6 text-base leading-7 text-[#536178]">Uma landing page focada em oferta, campanha ou intenção — conectada ao mesmo motor, às mesmas metas e à atribuição de origem.</p></div><div className="relative overflow-hidden rounded-[32px] bg-[#07172f] p-7 text-white sm:p-10"><div className="sobe-gradient-rule absolute inset-x-0 top-0" /><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[.14em]">Fluxo de campanha</span><Link2 className="text-[#02e5cd]" size={20} /></div><div className="mt-10 grid gap-3 sm:grid-cols-3">{[["Meta Ads", "Entrada"], ["Landing", "Contexto"], ["Orçamento", "Conversão"]].map(([title, note], index) => <div key={title} className="relative rounded-[18px] bg-white/10 p-5"><small className="text-[#02e5cd]">0{index + 1} · {note}</small><strong className="mt-6 block">{title}</strong></div>)}</div></div></div></section>

    <section className="bg-[#e9fffc] py-24 sm:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><FileText className="text-[#0054fc]" /><h2 className="text-balance mt-6 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Presença comercial, não um construtor genérico.</h2></div><div className="grid content-start gap-5 text-sm leading-7 text-[#625e6a]"><p className="text-lg font-bold text-[#29272f]">Pode substituir landing pages e sites comerciais enxutos quando o objetivo principal é apresentar o negócio e converter visitantes em ação.</p><p>Uma presença comercial navegável, com conteúdo, oferta, mídia, informações, SEO básico e CTAs ligados a ações comerciais.</p><p>Não tenta ser portal, CMS editorial complexo, grande e-commerce, marketplace, ERP, CRM completo ou web app arbitrário.</p></div></div></section>

    <section className="py-24 sm:py-32"><div className="container-shell"><div className="relative overflow-hidden rounded-[36px] bg-[#07172f] px-6 py-16 text-center text-white sm:px-14 sm:py-24"><div className="sobe-gradient-rule absolute inset-x-0 top-0" /><Target className="mx-auto text-[#02e5cd]" /><h2 className="text-balance mx-auto mt-6 max-w-4xl text-4xl font-extrabold tracking-[-.055em] sm:text-6xl">Sua presença pode transformar atenção em oportunidade.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-white/60">Apresente seu negócio, conecte cada intenção ao próximo passo e acompanhe o que realmente virou resultado.</p><Link href="/app/onboarding" className="focus-ring mt-8 inline-flex min-h-14 items-center gap-2 rounded-2xl bg-white px-6 font-extrabold text-[#07172f] transition hover:bg-[#e9fffc]">Criar minha Sobe <ArrowRight size={18} /></Link></div></div></section><MarketingFooter />
  </main>;
}
