import Link from "next/link";
import { ArrowRight, BarChart3, BrainCircuit, Check, CircleDot, Link2, MousePointerClick, Route, ScanLine, Sparkles, Target } from "lucide-react";
import { MarketingFooter, MarketingHeader } from "@/components/marketing/header";
import { ConversionDemo } from "@/components/marketing/conversion-demo";

const traditional = ["Mostra destinos sem entender intenção", "Mistura campanhas em uma URL genérica", "Conta cliques, mas não confirma conversão"];
const virou = ["Pergunta o que a pessoa quer", "Abre a jornada certa para cada entrada", "Conecta ação, oportunidade e conversão confirmada"];

export default function HomePage() {
  return <main className="overflow-hidden bg-[#f6f5f1] text-[#18181d]"><MarketingHeader />
    <section className="relative pb-24 pt-36 sm:pt-44"><div className="pointer-events-none absolute inset-0 marketing-grid opacity-40" /><div className="container-shell relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="max-w-[720px]"><div className="inline-flex items-center gap-2 rounded-full border border-[#d8d3f2] bg-white px-3 py-2 text-xs font-bold text-[#594bc8]"><ScanLine size={14} /> Conversão para o tráfego social</div><h1 className="text-balance mt-7 text-[clamp(3.25rem,7.5vw,6.8rem)] font-extrabold leading-[.91] tracking-[-.07em]">Transforme quem chega das suas redes em cliente.</h1><p className="text-balance mt-7 max-w-[650px] text-lg leading-8 text-[#66636d] sm:text-xl">Entenda o que cada visitante quer e conduza-o até pedido, orçamento, agendamento, reserva ou atendimento — com origem, intenção e resultado no mesmo fluxo.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/app/onboarding" className="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-[#19191e] px-6 font-bold text-white shadow-[0_16px_38px_rgba(25,25,30,.18)]">Começar grátis <ArrowRight size={18} /></Link><a href="#como-funciona" className="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-[#d9d6df] bg-white px-6 font-bold">Ver como funciona <MousePointerClick size={18} /></a></div><p className="mt-6 text-xs font-medium text-[#7c7983]">Sem promessa mágica. Você configura os caminhos, publica e confirma o que realmente converteu.</p></div><ConversionDemo /></div></section>

    <section className="bg-[#19191e] py-24 text-white"><div className="container-shell"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#9f92ff]">Links organizam. Virou conduz.</span><h2 className="text-balance mt-5 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Não basta saber onde clicaram. É preciso saber o que queriam.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="border-t border-white/15 pt-6"><span className="text-sm font-bold text-white/45">Página de links tradicional</span><ul className="mt-7 space-y-4">{traditional.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-white/65"><CircleDot className="mt-1 shrink-0" size={14} />{item}</li>)}</ul></div><div className="border-t border-[#8d7eff] pt-6"><span className="text-sm font-bold text-[#aa9fff]">Infraestrutura Virou</span><ul className="mt-7 space-y-4">{virou.map((item) => <li key={item} className="flex gap-3 text-sm font-semibold leading-6"><Check className="mt-1 shrink-0 text-[#9f91ff]" size={15} />{item}</li>)}</ul></div></div></div></div></section>

    <section id="como-funciona" className="py-24 sm:py-32"><div className="container-shell"><div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-[.16em] text-[#6254d4]">Da atenção à conversão</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">Um sistema contínuo, não uma coleção de botões.</h2></div><div className="mt-16 grid gap-2 md:grid-cols-6 md:items-center">{[["Atenção", "Chegada", MousePointerClick], ["Intenção", "Meta", Target], ["Jornada", "Caminho", Route], ["Ação", "Pedido", Sparkles], ["Oportunidade", "Contexto", BrainCircuit], ["Conversão", "Confirmada", Check]].map(([label, note, Icon], index) => { const StepIcon = Icon as typeof Target; return <div key={String(label)} className="relative border-l border-[#d8d5df] py-3 pl-4 md:border-l-0 md:border-t md:pb-0 md:pl-0 md:pt-5"><span className="absolute -left-1 top-5 size-2 rounded-full bg-[#6b5cdb] md:-top-1 md:left-0" /><StepIcon size={19} className="text-[#6254d4]" /><strong className="mt-7 block text-sm">{String(label)}</strong><span className="mt-1 block text-xs text-[#817e87]">{String(note)}</span><small className="absolute right-2 top-4 text-[#aaa6b1] md:right-4 md:top-6">0{index + 1}</small></div>; })}</div></div></section>

    <section className="border-y border-[#e2dfe5] bg-white py-24 sm:py-32"><div className="container-shell grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#6254d4]">Muitas entradas. Um motor.</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Cada canal abre a conversa no ponto certo.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#6d6974]">Bio, Story, anúncio, LinkedIn e QR code podem compartilhar a mesma jornada e, ainda assim, preservar campanha, origem e intenção.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Bio", "Visão geral", Link2], ["Story Delivery", "Pedir agora", MousePointerClick], ["Meta Revenda", "Comprar para revenda", Target], ["QR da unidade", "Encontrar uma unidade", ScanLine]].map(([name, goal, Icon]) => { const EntryIcon = Icon as typeof Link2; return <div key={String(name)} className="rounded-[20px] border border-[#e2dfe6] p-5"><EntryIcon size={18} className="text-[#6657d8]" /><strong className="mt-8 block">{String(name)}</strong><span className="mt-1 block text-xs text-[#7a7681]">Abre em: {String(goal)}</span></div>; })}</div></div></section>

    <section className="py-24 sm:py-32"><div className="container-shell grid gap-14 lg:grid-cols-2 lg:items-center"><div className="rounded-[30px] bg-[#1a1920] p-6 text-white sm:p-9"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#a99fff]">Roteamento com contexto</span><Route size={20} /></div><div className="mt-12 space-y-3"><div className="rounded-[17px] border border-white/10 p-4"><span className="text-[10px] text-white/45">SE</span><strong className="ml-3 text-sm">Meta = pedir orçamento</strong></div><div className="ml-8 h-6 border-l border-dashed border-white/25" /><div className="rounded-[17px] border border-[#8f80ff]/45 bg-[#292638] p-4"><span className="text-[10px] text-[#a99fff]">ENTÃO</span><strong className="ml-3 text-sm">Qualificar → recomendar → atender</strong></div></div></div><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#6254d4]">O próximo passo correto</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">A mesma pessoa não precisa ver todos os caminhos.</h2><p className="mt-6 text-base leading-7 text-[#6d6974]">Metas e regras conectam intenção, informações necessárias e destino. Quando o contato chega ao WhatsApp, ele pode levar o contexto reunido — sem prometer automação de mensagens.</p></div></div></section>

    <section className="bg-[#ece9ff] py-24 sm:py-32"><div className="container-shell"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#5a4acb]">Analytics de conversão</span><h2 className="text-balance mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Veja o funil real, sem números decorativos.</h2><p className="mt-6 text-sm leading-7 text-[#676272]">Sessões, metas, ações, oportunidades e conversões confirmadas. Comparações só aparecem quando existe um período anterior válido.</p></div><div className="rounded-[26px] bg-white p-6 shadow-[0_24px_60px_rgba(58,47,115,.12)]"><div className="flex items-center justify-between"><strong>Exemplo ilustrativo</strong><span className="rounded-full bg-[#f2f0f5] px-2.5 py-1 text-[10px] font-bold">Dados de demonstração</span></div><div className="mt-8 grid grid-cols-5 gap-2">{[["Atenção", 100], ["Intenção", 72], ["Ação", 43], ["Oportunidade", 21], ["Conversão", 8]].map(([label, value]) => <div key={String(label)} className="flex flex-col justify-end"><div className="rounded-t-lg bg-[#7465de]" style={{ height: `${Number(value) * 1.25}px`, opacity: .35 + Number(value) / 160 }} /><strong className="mt-2 text-sm">{Number(value)}</strong><span className="mt-1 text-[9px] text-[#77727f]">{String(label)}</span></div>)}</div></div></div></div></section>

    <section className="py-24 sm:py-32"><div className="container-shell grid gap-5 lg:grid-cols-2"><div className="rounded-[30px] border border-[#dfdce4] bg-white p-8 sm:p-10"><BrainCircuit size={25} className="text-[#6455d6]" /><h2 className="mt-14 text-3xl font-extrabold tracking-[-.04em]">IA que explica evidências.</h2><p className="mt-4 text-sm leading-7 text-[#6f6b75]">A Virou pode traduzir sinais em uma sugestão clara. A regra e os dados vêm primeiro; a IA não inventa desempenho e nunca publica uma mudança sozinha.</p></div><div className="rounded-[30px] bg-[#f06e5d] p-8 text-[#2b1714] sm:p-10"><BarChart3 size={25} /><h2 className="mt-14 text-3xl font-extrabold tracking-[-.04em]">Otimização com limite mínimo.</h2><p className="mt-4 text-sm leading-7 text-[#552b25]">Sugestões só aparecem com evidência suficiente: pelo menos 30 sessões no negócio e 15 na meta analisada.</p></div></div></section>

    <section className="pb-24 sm:pb-32"><div className="container-shell"><div className="rounded-[36px] bg-[#19191e] px-6 py-16 text-center text-white sm:px-14 sm:py-24"><Target className="mx-auto text-[#a99fff]" /><h2 className="text-balance mx-auto mt-6 max-w-4xl text-4xl font-extrabold tracking-[-.055em] sm:text-6xl">Não mostre seus links. Mostre o próximo passo.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-white/60">Modele as intenções, publique entradas específicas e acompanhe o que virou oportunidade.</p><Link href="/app/onboarding" className="focus-ring mt-8 inline-flex min-h-14 items-center gap-2 rounded-2xl bg-white px-6 font-extrabold text-[#292335]">Criar minha Virou <ArrowRight size={18} /></Link></div></div></section><MarketingFooter /></main>;
}
