import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { activationExpiry } from "@/features/activations/activation-utils";
import { ActivationRepository } from "@/server/activations/activation-repository";
import { evaluateActivationEligibility } from "@/server/activations/evaluate-activation-eligibility";
import { CustomerIdentityRepository } from "@/server/customer-identity/customer-identity-repository";
import { resolveOrCreateCustomerIdentity } from "@/server/customer-identity/customer-identity-service";
import { resolveCustomerHistory } from "@/server/customer-identity/eligibility-history";
import { BenefitRepository } from "./benefit-repository";
import { generateClaimCode } from "./claim-code";
export async function issueBenefitClaim(database:SupabaseClient,input:{workspaceId:string;projectId:string;activationId:string;sessionKey:string;phone?:string;email?:string;locationId?:string;entryPointId?:string;defaultCountry?:string}){const activation=await new ActivationRepository(database).get(input.projectId,input.activationId);if(!activation)throw new Error("invalid_activation");const customer=await resolveOrCreateCustomerIdentity(database,{...input});const identityRepository=new CustomerIdentityRepository(database);const evidence=await identityRepository.evidence(customer.id);const coverage={status:evidence.some((item)=>item.evidenceType==="external_customer")?"external_sync":evidence.some((item)=>item.evidenceType==="historical_customer_import")?"historical_import":"virou_only",sourceCount:new Set(evidence.filter((item)=>["historical_customer_import","external_customer"].includes(item.evidenceType)).map((item)=>item.sourceId)).size} as const;const benefitRepository=new BenefitRepository(database);const counts=await benefitRepository.counts(activation.id,customer.id);const eligibility=evaluateActivationEligibility({activation,offer:activation.offers[0],customerIdentity:customer,evidence,coverage,context:{locationId:input.locationId,entryPointId:input.entryPointId},counts});if(!eligibility.eligible)return{eligible:false,reason:eligibility.code,message:eligibility.publicMessage} as const;const {data:session}=await database.from("visitor_sessions").select("id").eq("project_id",input.projectId).eq("session_key",input.sessionKey).maybeSingle();let claim;for(let attempt=0;attempt<5;attempt++){try{claim=await benefitRepository.issue({projectId:input.projectId,activationId:activation.id,offerId:activation.offers[0]?.id,customerIdentityId:customer.id,sessionId:session?.id,code:generateClaimCode(),expiresAt:activationExpiry(activation.endsAt,Number(activation.settings.claimTtlMinutes||1440)),eligibility:eligibility.evidence,benefit:{...activation.offers[0],activationVersion:activation.version}});break;}catch(error){if(error&&typeof error==="object"&&"message" in error&&String(error.message).includes("duplicate"))continue;throw error;}}if(!claim)throw new Error("claim_generation_failed");if(session?.id)await database.from("visitor_sessions").update({customer_identity_id:customer.id,activation_id:activation.id,benefit_claim_id:claim.id}).eq("id",session.id);await database.from("analytics_events").insert([{project_id:input.projectId,session_id:session?.id,event_name:"customer_identified",activation_id:activation.id,metadata:{identityState:resolveCustomerHistory(evidence,coverage).state}},{project_id:input.projectId,session_id:session?.id,event_name:"benefit_claim_issued",activation_id:activation.id,benefit_claim_id:claim.id,metadata:{}}]);return{eligible:true,claim:{id:claim.id,code:claim.code,benefitLabel:activation.offers[0]?.label||activation.title||activation.name,expiresAt:claim.expires_at}} as const;}
