import "server-only";
import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { createServiceClient } from "@/lib/supabase/server";
import { assertProjectAccess } from "@/server/auth/project-access";
import type { AuthenticatedActor } from "@/server/auth/setup-actor";
import type { MediaAsset } from "@/types";

const imageTypes = new Set(["image/png", "image/jpeg", "image/webp"]);
const assetTypes = new Set(["logo", "favicon", "image", "video", "background", "product", "service", "accommodation", "portfolio", "testimonial", "document_preview"]);
function database() { const client = createServiceClient(); if (!client) throw new Error("Configure o Supabase para usar a biblioteca de mídia."); return client; }
function cleanName(value: string) { return value.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-").slice(0, 180) || "asset"; }
function detect(buffer: Buffer): string { if (buffer.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) return "image/png"; if (buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) return "image/jpeg"; if (buffer.subarray(0, 4).toString() === "RIFF" && buffer.subarray(8, 12).toString() === "WEBP") return "image/webp"; if (buffer.subarray(4, 8).toString() === "ftyp") return "video/mp4"; if (buffer.subarray(0, 4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3]))) return "video/webm"; throw new Error("Assinatura de mídia não permitida. SVG está desativado no beta por segurança."); }
function fromRow(row: Record<string, unknown>, url?: string | null, thumbnailUrl?: string | null): MediaAsset & { url?: string; thumbnailUrl?: string } { return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: row.project_id ? String(row.project_id) : undefined, storagePath: String(row.storage_path), originalName: String(row.original_filename || "asset"), mimeType: String(row.mime_type), byteSize: Number(row.file_size || 0), width: row.width == null ? undefined : Number(row.width), height: row.height == null ? undefined : Number(row.height), durationSeconds: row.duration_seconds == null ? undefined : Number(row.duration_seconds), assetType: row.asset_type as MediaAsset["assetType"], status: row.status as MediaAsset["status"], altText: row.alt_text ? String(row.alt_text) : undefined, tags: Array.isArray(row.tags) ? row.tags.map(String) : [], metadata: (row.metadata || {}) as Record<string, unknown>, createdAt: String(row.created_at), updatedAt: row.updated_at ? String(row.updated_at) : undefined, url: url ?? undefined, thumbnailUrl: thumbnailUrl ?? undefined }; }
async function signedUrls(row: Record<string, unknown>) { const client = database(); const metadata = (row.metadata || {}) as Record<string, unknown>; const paths = [String(row.storage_path), typeof metadata.thumbnailPath === "string" ? metadata.thumbnailPath : ""]; const { data } = await client.storage.from("media-private").createSignedUrls(paths.filter(Boolean), 3600); return { url: data?.[0]?.signedUrl, thumbnailUrl: paths[1] ? data?.[1]?.signedUrl : data?.[0]?.signedUrl }; }
export async function listMedia(actor: AuthenticatedActor, projectId: string) { await assertProjectAccess(actor, projectId, "read"); if (actor.persistence === "memory") return []; const { data, error } = await database().from("media_assets").select("*").eq("project_id", projectId).eq("workspace_id", actor.workspaceId).order("created_at", { ascending: false }); if (error) throw new Error("Não foi possível carregar a biblioteca."); return Promise.all((data || []).map(async (row) => { const urls = await signedUrls(row); return fromRow(row, urls.url, urls.thumbnailUrl); })); }
export async function uploadMedia(actor: AuthenticatedActor, projectId: string, file: File, input: { assetType?: string; altText?: string; tags?: string[] }) { await assertProjectAccess(actor, projectId, "write"); if (actor.persistence === "memory") throw new Error("Configure o Supabase para enviar mídia persistente."); if (!file.size || file.size > 20 * 1024 * 1024) throw new Error("A mídia deve ter no máximo 20 MB."); const buffer = Buffer.from(await file.arrayBuffer()); const mimeType = detect(buffer); if (imageTypes.has(mimeType) && buffer.length > 15 * 1024 * 1024) throw new Error("Imagens devem ter no máximo 15 MB."); const id = randomUUID(); const name = cleanName(file.name); const originalPath = `${actor.workspaceId}/${projectId}/${id}/original-${name}`; const client = database(); let width: number | undefined; let height: number | undefined; let metadata: Record<string, unknown> = {}; if (imageTypes.has(mimeType)) { const image = sharp(buffer, { limitInputPixels: 40_000_000 }); const info = await image.metadata(); width = info.width; height = info.height; if (!width || !height || width > 10_000 || height > 10_000) throw new Error("Dimensões de imagem inválidas."); const [optimized, thumbnail] = await Promise.all([image.clone().rotate().resize({ width: 2400, height: 2400, fit: "inside", withoutEnlargement: true }).webp({ quality: 84 }).toBuffer(), image.clone().rotate().resize({ width: 480, height: 480, fit: "inside", withoutEnlargement: true }).webp({ quality: 76 }).toBuffer()]); const optimizedPath = `${actor.workspaceId}/${projectId}/${id}/optimized.webp`; const thumbnailPath = `${actor.workspaceId}/${projectId}/${id}/thumbnail.webp`; const uploads = await Promise.all([client.storage.from("media-private").upload(originalPath, buffer, { contentType: mimeType }), client.storage.from("media-private").upload(optimizedPath, optimized, { contentType: "image/webp" }), client.storage.from("media-private").upload(thumbnailPath, thumbnail, { contentType: "image/webp" })]); if (uploads.some((result) => result.error)) throw new Error("Não foi possível armazenar as versões da imagem."); metadata = { optimizedPath, thumbnailPath }; } else { const { error } = await client.storage.from("media-private").upload(originalPath, buffer, { contentType: mimeType }); if (error) throw new Error("Não foi possível armazenar o vídeo."); }
  const assetType = assetTypes.has(input.assetType || "") ? input.assetType : mimeType.startsWith("video/") ? "video" : "image"; const { data, error } = await client.from("media_assets").insert({ id, workspace_id: actor.workspaceId, project_id: projectId, uploaded_by: actor.userId, asset_type: assetType, storage_path: originalPath, original_filename: name, mime_type: mimeType, width: width || null, height: height || null, file_size: buffer.length, alt_text: input.altText || null, tags: input.tags || [], status: "ready", metadata }).select("*").single(); if (error) { await client.storage.from("media-private").remove([originalPath, ...Object.values(metadata).map(String)]); throw new Error("Não foi possível registrar a mídia."); } const urls = await signedUrls(data); return fromRow(data, urls.url, urls.thumbnailUrl); }
export async function updateMedia(actor: AuthenticatedActor, projectId: string, assetId: string, input: { altText?: string; tags?: string[]; assetType?: string }) { await assertProjectAccess(actor, projectId, "write"); const patch: Record<string, unknown> = {}; if (input.altText !== undefined) patch.alt_text = input.altText || null; if (input.tags) patch.tags = [...new Set(input.tags.map((tag) => tag.trim().toLowerCase()).filter(Boolean))].slice(0, 20); if (input.assetType && assetTypes.has(input.assetType)) patch.asset_type = input.assetType; const { data, error } = await database().from("media_assets").update(patch).eq("id", assetId).eq("project_id", projectId).eq("workspace_id", actor.workspaceId).select("*").single(); if (error) throw new Error("Não foi possível atualizar a mídia."); const urls = await signedUrls(data); return fromRow(data, urls.url, urls.thumbnailUrl); }
export async function mediaUsage(actor: AuthenticatedActor, projectId: string, assetId: string) { await assertProjectAccess(actor, projectId, "read"); const client = database(); const [services, items, brands, units] = await Promise.all([client.from("service_offerings").select("id,name").eq("project_id", projectId).eq("image_asset_id", assetId), client.from("catalog_items").select("id,name").eq("project_id", projectId).eq("image_asset_id", assetId), client.from("brand_profiles").select("project_id").eq("project_id", projectId).or(`primary_logo_asset_id.eq.${assetId},light_logo_asset_id.eq.${assetId},dark_logo_asset_id.eq.${assetId},favicon_asset_id.eq.${assetId}`), client.from("reservable_units").select("id,name").eq("project_id", projectId).contains("media_asset_ids", [assetId])]); return [...(services.data || []).map((item) => ({ type: "service", ...item })), ...(items.data || []).map((item) => ({ type: "product", ...item })), ...(brands.data || []).map((item) => ({ type: "brand", id: item.project_id, name: "Identidade da marca" })), ...(units.data || []).map((item) => ({ type: "accommodation", ...item }))]; }
export async function deleteMedia(actor: AuthenticatedActor, projectId: string, assetId: string, force = false) { await assertProjectAccess(actor, projectId, "write"); const client = database(); const { data: project } = await client.from("projects").select("status").eq("id", projectId).eq("workspace_id", actor.workspaceId).single(); const usage = await mediaUsage(actor, projectId, assetId); if (usage.length && (project?.status === "published" || !force)) throw new Error(project?.status === "published" ? "Mídia em uso em um projeto publicado. Substitua as referências antes de excluir." : "Mídia em uso. Confirme a exclusão forçada ou substitua as referências."); const { data: row } = await client.from("media_assets").select("*").eq("id", assetId).eq("project_id", projectId).eq("workspace_id", actor.workspaceId).maybeSingle(); if (!row) throw new Error("Mídia não encontrada."); const metadata = (row.metadata || {}) as Record<string, unknown>; const paths = [row.storage_path, metadata.optimizedPath, metadata.thumbnailPath].filter((value): value is string => typeof value === "string"); const { error: storageError } = await client.storage.from("media-private").remove(paths); if (storageError) throw new Error("Não foi possível remover os arquivos da mídia."); const { error } = await client.from("media_assets").delete().eq("id", assetId).eq("project_id", projectId).eq("workspace_id", actor.workspaceId); if (error) throw new Error("Não foi possível remover o registro da mídia."); await client.from("commercial_audit_log").insert({ workspace_id: actor.workspaceId, project_id: projectId, actor_id: actor.userId, object_type: "media_asset", object_id: assetId, action: "deleted", before_state: row }); return { deleted: true }; }
