"use client";
import Link from "next/link";
import { ArrowLeft, Check, Loader2, Plus, Save, Target, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ConversionGoalCard } from "./conversion-goal-card";
import { ConversionOverview } from "./conversion-overview";
import { backfillConversionGoals } from "@/features/conversion-goals/utils";
import { setProjectConversionGoals } from "@/features/conversion-goals/service";
import { projectRepository } from "@/lib/repositories/project-repository";
import type { ConversionGoal, Project } from "@/types";

export function ConversionPage({ projectId }: { projectId: string }) {
  const [project, setProject] = useState<Project | null>(); const [goals, setGoals] = useState<ConversionGoal[]>([]); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void projectRepository.getProject(projectId).then((found) => { setProject(found || null); if (found) setGoals(backfillConversionGoals(found)); }).catch(() => setProject(null)); }, [projectId]);
  if (project === undefined) return <div className="h-80 animate-pulse rounded-[24px] bg-white" />;
  if (!project) return <div className="rounded-[24px] bg-white p-10 text-center"><h1 className="font-extrabold">Negócio não encontrado</h1></div>;
  const patchGoal = (id: string, patch: Partial<ConversionGoal>) => setGoals((items) => items.map((goal) => goal.id === id ? { ...goal, ...patch, ...(patch.isPrimary ? { isPrimary: true } : {}) } : patch.isPrimary ? { ...goal, isPrimary: false } : goal));
  async function save() { setSaving(true); setError(""); try { const updated = setProjectConversionGoals(project!, goals.map((goal, order) => ({ ...goal, order }))); const persisted = await projectRepository.saveProject(updated); setProject(persisted); setGoals(persisted.conversionGoals || goals); setSaved(true); setTimeout(() => setSaved(false), 1800); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  return <div className="animate-enter"><header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Link href={`/app/projects/${project.id}`} className="inline-flex items-center gap-2 text-xs font-bold text-[#74727d]"><ArrowLeft size={14} /> {project.name}</Link><div className="mt-4 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-[15px] bg-[#eaf3ff] text-[#0054fc]"><Target /></span><div><h1 className="text-3xl font-extrabold tracking-[-.045em]">Conversão</h1><p className="mt-1 text-sm text-[#74727d]">Defina intenções e conecte cada uma ao ponto certo da jornada.</p></div></div></div><Button onClick={() => void save()} disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : saved ? <Check /> : <Save />}{saving ? "Salvando" : saved ? "Salvo" : "Salvar metas"}</Button></header>
  <div className="mt-7"><ConversionOverview project={{ ...project, conversionGoals: goals }} /></div>
  <section className="mt-7 grid gap-5 xl:grid-cols-[.86fr_1.14fr]"><div><div className="flex items-end justify-between"><div><h2 className="text-xl font-extrabold">Metas de conversão</h2><p className="mt-1 text-xs text-[#7a7882]">A meta principal atende acessos sem entrada específica.</p></div><Button variant="secondary" onClick={() => setGoals((items) => [...items, { id: crypto.randomUUID(), projectId: project.id, name: "Nova meta", kind: "custom", targetStepId: project.steps[0]?.id || "", isPrimary: !items.length, isActive: true, order: items.length }])}><Plus /> Meta</Button></div><div className="mt-4 grid gap-3">{goals.map((goal) => <ConversionGoalCard key={goal.id} goal={goal} step={project.steps.find((step) => step.id === goal.targetStepId)} />)}</div></div>
  <div className="rounded-[24px] border border-[#e2e0e8] bg-white p-5 sm:p-6"><h2 className="font-extrabold">Configuração</h2><div className="mt-5 grid gap-5">{goals.map((goal, index) => <fieldset key={goal.id} className="rounded-[18px] border border-[#e7e5ec] p-4"><legend className="px-2 text-xs font-bold text-[#77747f]">Meta {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Nome<input value={goal.name} onChange={(event) => patchGoal(goal.id, { name: event.target.value })} className="mt-2 min-h-11 w-full rounded-xl border border-[#dddbe4] px-3 text-sm font-medium" /></label><label className="text-xs font-bold">Tipo<select value={goal.kind} onChange={(event) => patchGoal(goal.id, { kind: event.target.value as ConversionGoal["kind"] })} className="mt-2 min-h-11 w-full rounded-xl border border-[#dddbe4] bg-white px-3 text-sm"><option value="buy">Comprar</option><option value="request_quote">Pedir orçamento</option><option value="schedule">Agendar</option><option value="reserve">Reservar</option><option value="contact">Falar</option><option value="visit">Visitar</option><option value="learn">Conhecer</option><option value="custom">Personalizada</option></select></label><label className="text-xs font-bold sm:col-span-2">Descrição<textarea value={goal.description || ""} onChange={(event) => patchGoal(goal.id, { description: event.target.value })} className="mt-2 min-h-20 w-full rounded-xl border border-[#dddbe4] p-3 text-sm" /></label><label className="text-xs font-bold">Início da jornada<select value={goal.targetStepId} onChange={(event) => patchGoal(goal.id, { targetStepId: event.target.value })} className="mt-2 min-h-11 w-full rounded-xl border border-[#dddbe4] bg-white px-3 text-sm">{project.steps.map((step) => <option key={step.id} value={step.id}>{step.title}</option>)}</select></label><div className="flex items-end justify-between gap-3"><label className="flex min-h-11 items-center gap-2 text-xs font-bold"><input type="radio" name="primary-goal" checked={goal.isPrimary} onChange={() => patchGoal(goal.id, { isPrimary: true })} /> Meta principal</label><Button variant="ghost" size="icon" aria-label="Excluir meta" disabled={goals.length === 1} onClick={() => setGoals((items) => items.filter((item) => item.id !== goal.id))}><Trash2 /></Button></div></div></fieldset>)}</div>{error ? <p role="alert" className="mt-4 text-sm font-semibold text-red-600">{error}</p> : null}</div></section></div>;
}
