"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, Bike, BookOpen, Building2, CalendarCheck, Check, ChevronRight, Compass, FileText, LineChart, LoaderCircle, Mail, MapPin, MessageCircle, MessageSquare, Share2, ShoppingBag, Sparkles, Store, Target, TrendingUp } from "lucide-react";
import { localStore } from "@/lib/local-store";
import { buildWhatsAppMessage, buildWhatsAppUrl } from "@/features/whatsapp/whatsapp";
import { uid } from "@/lib/utils";
import type { AnalyticsEvent, FormField, JourneyStep, Project, StepOption } from "@/types";

const iconMap = { ShoppingBag, BookOpen, MapPin, Building2, Bike, Store, Target, LineChart, TrendingUp, MessageSquare, MessageCircle, CalendarCheck, FileText, Mail, Sparkles, Compass, ArrowUpRight };

function DynamicIcon({ name }: { name?: string }) { const Icon = iconMap[name as keyof typeof iconMap] || ArrowRight; return <Icon size={19} />; }

function FieldControl({ field, value, onChange, onFocus }: { field: FormField; value: string; onChange: (value: string) => void; onFocus: () => void }) {
  const style = "min-h-12 w-full rounded-[var(--input-radius)] border border-[var(--border)] bg-[var(--surface)] px-3.5 text-sm text-[var(--foreground)] outline-none transition focus:ring-4 focus:ring-[var(--primary)]/10";
  if (field.type === "select") return <select aria-label={field.label} required={field.required} value={value} onChange={(event) => onChange(event.target.value)} onFocus={onFocus} className={style}><option value="">Selecione</option>{field.options?.map((item) => <option key={item}>{item}</option>)}</select>;
  if (field.type === "radio") return <div className="grid gap-2">{field.options?.map((item) => <label key={item} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-[var(--input-radius)] border px-3.5 text-sm font-semibold ${value === item ? "border-[var(--primary)] bg-[var(--muted)]" : "border-[var(--border)] bg-[var(--surface)]"}`}><input type="radio" name={field.id} value={item} checked={value === item} onChange={() => onChange(item)} onFocus={onFocus} className="accent-[var(--primary)]" />{item}</label>)}</div>;
  if (field.type === "checkbox") return <label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={value === "true"} onChange={(event) => onChange(String(event.target.checked))} onFocus={onFocus} className="mt-1 accent-[var(--primary)]" /><span>{field.placeholder || field.label}</span></label>;
  if (field.type === "textarea") return <textarea aria-label={field.label} required={field.required} value={value} onChange={(event) => onChange(event.target.value)} onFocus={onFocus} placeholder={field.placeholder} className={`${style} min-h-24 py-3`} />;
  return <input aria-label={field.label} required={field.required} type={field.type === "phone" ? "tel" : field.type} value={value} onChange={(event) => onChange(event.target.value)} onFocus={onFocus} placeholder={field.placeholder} className={style} />;
}

function SpecialBlocks({ step }: { step: JourneyStep }) {
  return <>{step.blocks?.map((block) => {
    if (block.type === "location_card") { const content = block.content as { name?: string; eta?: string; status?: string; address?: string }; return <div key={block.id} className="rounded-[var(--card-radius)] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--card-shadow)]"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--muted)] text-[var(--primary)]"><MapPin size={21} /></span><div><strong className="block text-lg">{content.name}</strong><span className="mt-1 block text-xs text-[var(--muted-fg)]">{content.address}</span></div></div><div className="mt-4 flex gap-2"><span className="rounded-full bg-[var(--muted)] px-3 py-1.5 text-xs font-bold">{content.eta}</span><span className="rounded-full bg-[#e8f7ef] px-3 py-1.5 text-xs font-bold text-[#147b58]">{content.status}</span></div></div>; }
    if (block.type === "product_cards") { const content = block.content as { products?: Array<{ name: string; price: string; emoji: string }> }; return <div key={block.id} className="grid gap-2">{content.products?.map((product) => <button type="button" key={product.name} className="flex items-center gap-3 rounded-[var(--card-radius)] border border-[var(--border)] bg-[var(--surface)] p-3 text-left shadow-[var(--card-shadow)]"><span className="grid size-12 place-items-center rounded-2xl bg-[var(--muted)] text-2xl">{product.emoji}</span><span className="flex-1"><strong className="block text-sm">{product.name}</strong><small className="text-[var(--muted-fg)]">{product.price}</small></span><ChevronRight size={18} className="text-[var(--primary)]" /></button>)}</div>; }
    if (block.type === "schedule_slots") { const content = block.content as { slots?: string[] }; return <div key={block.id} className="grid grid-cols-2 gap-2">{content.slots?.map((slot, index) => <button type="button" key={slot} className={`min-h-11 rounded-[var(--input-radius)] border px-3 text-xs font-bold ${index === 0 ? "border-[var(--primary)] bg-[var(--muted)] text-[var(--primary)]" : "border-[var(--border)] bg-[var(--surface)]"}`}>{slot}</button>)}</div>; }
    return null;
  })}</>;
}

export function ExperienceCanvas({ project, preview = false }: { project: Project; preview?: boolean }) {
  const activeSteps = useMemo(() => project.steps.filter((step) => step.isActive).sort((a, b) => a.order - b.order), [project]);
  const storageKey = `smartbio:session:${project.slug}`;
  const restored = typeof window !== "undefined" && !preview ? (() => { try { return JSON.parse(localStorage.getItem(storageKey) || "null") as { visitorId: string; sessionId: string; answers: Record<string, string>; stepId?: string } | null; } catch { return null; } })() : null;
  const [currentId, setCurrentId] = useState(restored?.stepId || activeSteps[0]?.id); const [answers, setAnswers] = useState<Record<string, string>>(restored?.answers || {}); const [history, setHistory] = useState<string[]>([]); const [leadForm, setLeadForm] = useState(false); const [submitted, setSubmitted] = useState(false); const formStarted = useRef(false);
  const visitorId = useRef(restored?.visitorId || uid("visitor")); const sessionId = useRef(restored?.sessionId || uid("session"));
  const step = activeSteps.find((item) => item.id === currentId) || activeSteps[0]; const stepIndex = Math.max(0, activeSteps.findIndex((item) => item.id === step?.id));
  const palette = project.designSystem.colors;

  function event(eventName: AnalyticsEvent["eventName"], input?: { optionId?: string; metadata?: Record<string, unknown> }) {
    if (preview || !step) return;
    const params = new URLSearchParams(location.search);
    const payload = { projectId: project.id, visitorId: visitorId.current, sessionId: sessionId.current, eventName, stepId: step.id, optionId: input?.optionId, metadata: input?.metadata, referrer: document.referrer, utmSource: params.get("utm_source") || undefined, utmMedium: params.get("utm_medium") || undefined, utmCampaign: params.get("utm_campaign") || undefined, utmContent: params.get("utm_content") || undefined, utmTerm: params.get("utm_term") || undefined, deviceType: matchMedia("(max-width: 700px)").matches ? "mobile" : "desktop" };
    localStore.track(payload); void fetch("/api/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload), keepalive: true }).catch(() => undefined);
  }

  useEffect(() => { if (!step || preview) return; const value = { visitorId: visitorId.current, sessionId: sessionId.current, answers, stepId: step.id, startedAt: new Date().toISOString() }; localStorage.setItem(storageKey, JSON.stringify(value)); }, [answers, preview, step, storageKey]);
  useEffect(() => { if (preview || !step) return; event("page_view"); event("session_started"); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (preview || !step) return; event("step_viewed"); if (step.type === "recommendation") event("recommendation_viewed"); }, [currentId]); // eslint-disable-line react-hooks/exhaustive-deps

  function go(target?: string) { if (!target || !step) return; setHistory((items) => [...items, step.id]); setCurrentId(target); setLeadForm(false); setSubmitted(false); }
  function back() { const previous = history.at(-1); if (!previous) return; setHistory((items) => items.slice(0, -1)); setCurrentId(previous); setLeadForm(false); }
  function updateAnswer(key: string, value: string) { setAnswers((current) => ({ ...current, [key]: value })); }
  function formReady(fields = step?.formFields || []) { return fields.every((field) => !field.required || Boolean(answers[field.key])); }

  async function optionClicked(option: StepOption) {
    if (preview && option.actionType !== "go_to_step") return;
    event("option_clicked", { optionId: option.id, metadata: { value: option.value } }); updateAnswer(`escolha_${step.id}`, option.label);
    if (option.actionType === "go_to_step" || option.actionType === "show_recommendation") go(option.targetStepId);
    else if (option.actionType === "open_whatsapp") { const phone = String(option.actionPayload?.phone || project.phone || "5511999999999"); const message = buildWhatsAppMessage({ interest: step.recommendation?.title || answers[`escolha_${activeSteps[0]?.id}`], answers, closing: "Quero saber qual é o melhor próximo passo." }); event("whatsapp_clicked", { optionId: option.id }); window.open(buildWhatsAppUrl(phone, message), "_blank", "noopener,noreferrer"); }
    else if (option.actionType === "open_url") { event("external_link_clicked", { optionId: option.id }); window.open(String(option.actionPayload?.url || "https://example.com"), "_blank", "noopener,noreferrer"); }
    else if (option.actionType === "submit_form") setLeadForm(true);
    else if (option.actionType === "finish") { event("journey_completed"); setSubmitted(true); }
  }

  function submitStep(eventObject: React.FormEvent) { eventObject.preventDefault(); if (!step || !formReady()) return; event("form_submitted"); const continueOption = step.options?.find((option) => option.actionType === "go_to_step" || option.actionType === "show_recommendation"); if (continueOption) go(continueOption.targetStepId); else submitLead(); }
  function submitLead() {
    if (!step || !formReady(step.formFields || [])) return;
    const lead = { projectId: project.id, projectName: project.name, sessionId: sessionId.current, name: answers.name, email: answers.email, phone: answers.phone, company: answers.company || answers.negocio, status: "new" as const, source: new URLSearchParams(location.search).get("utm_source") || "direct", campaign: new URLSearchParams(location.search).get("utm_campaign") || undefined, recommendation: activeSteps.find((item) => item.type === "recommendation")?.recommendation?.title, answers };
    localStore.addLead(lead); void fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...lead, honeypot: "" }) }).catch(() => undefined); event("form_submitted"); event("journey_completed"); setSubmitted(true); setLeadForm(false);
  }
  async function share() { const data = { title: project.name, text: project.description, url: location.href }; if (navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(location.href); } }

  if (!step) return <div className="grid min-h-[420px] place-items-center text-sm">Esta experiência ainda não tem etapas ativas.</div>;
  const bodyFont = `"${project.designSystem.typography.bodyFont}", Inter, ui-sans-serif, system-ui, sans-serif`;
  const headingFont = `"${project.designSystem.typography.headingFont}", Inter, ui-sans-serif, system-ui, sans-serif`;
  const css = { "--primary": palette.primary, "--primary-fg": palette.primaryForeground, "--secondary": palette.secondary, "--accent": palette.accent, "--background": palette.background, "--surface": palette.surface, "--surface-elevated": palette.surfaceElevated, "--foreground": palette.foreground, "--muted": palette.muted, "--muted-fg": palette.mutedForeground, "--border": palette.border, "--card-radius": `${project.designSystem.shape.cardRadius}px`, "--button-radius": `${project.designSystem.shape.buttonRadius}px`, "--input-radius": `${project.designSystem.shape.inputRadius}px`, "--card-shadow": project.designSystem.elevation.cardShadow, fontFamily: bodyFont } as React.CSSProperties;
  return <div style={css} className={`relative flex h-full min-h-[560px] flex-col overflow-hidden bg-[var(--background)] text-[var(--foreground)] ${project.designSystem.mode === "dark" ? "dark" : ""}`}>
    <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute -right-24 -top-24 size-72 rounded-full bg-[var(--primary)] opacity-[.12] blur-3xl" /><div className="absolute -bottom-32 -left-20 size-72 rounded-full bg-[var(--accent)] opacity-[.1] blur-3xl" />{project.designSystem.imagery.decorativeStyle?.includes("grid") && <div className="dot-grid absolute inset-0 text-[var(--foreground)] opacity-[.055]" />}</div>
    <header className="relative flex items-center justify-between p-5"><div className="flex items-center gap-2">{history.length > 0 ? <button onClick={back} className="grid size-10 place-items-center rounded-full border border-[var(--border)] bg-[var(--surface)]" aria-label="Voltar"><ArrowLeft size={18} /></button> : project.brand.logoDataUrl ? <img src={project.brand.logoDataUrl} alt={`Logo ${project.name}`} className="h-9 max-w-28 object-contain" /> : <span className="grid size-10 place-items-center rounded-[14px] bg-[var(--primary)] text-xs font-extrabold text-[var(--primary-fg)]">{project.name.slice(0, 2).toUpperCase()}</span>}</div><div className="flex items-center gap-2"><span className="text-[11px] font-bold text-[var(--muted-fg)]">{stepIndex + 1} de {activeSteps.length}</span>{!preview && <button onClick={() => void share()} className="grid size-10 place-items-center rounded-full border border-[var(--border)] bg-[var(--surface)]" aria-label="Compartilhar"><Share2 size={17} /></button>}</div></header>
    <div className="relative mx-5 h-1 overflow-hidden rounded-full bg-[var(--muted)]"><motion.div className="h-full rounded-full bg-[var(--primary)]" animate={{ width: `${(stepIndex + 1) / activeSteps.length * 100}%` }} /></div>
    <main className="relative flex flex-1 flex-col overflow-y-auto px-5 pb-6 pt-8 scrollbar-thin sm:px-7"><AnimatePresence mode="wait"><motion.div key={step.id} initial={{ opacity: 0, x: project.designSystem.motion.transition === "slide" ? 18 : 0, scale: project.designSystem.motion.transition === "scale" ? .98 : 1 }} animate={{ opacity: 1, x: 0, scale: 1 }} exit={{ opacity: 0, x: -12 }} transition={{ duration: project.designSystem.motion.duration / 1000 }} className="flex min-h-full flex-col">
      <div><span className="text-[11px] font-extrabold uppercase tracking-[.16em] text-[var(--primary)]">{step.type === "recommendation" ? "Feito para você" : step.type === "form" ? "Só mais um passo" : step.type === "action" ? "Hora de avançar" : "Seu próximo passo"}</span><h1 className="text-balance mt-3 text-[clamp(2rem,8vw,3.4rem)] font-extrabold leading-[1.01] tracking-[-.052em]" style={{ fontFamily: headingFont }}>{step.title}</h1>{step.description && <p className="mt-3 max-w-md text-sm leading-6 text-[var(--muted-fg)]">{step.description}</p>}</div>
      {step.recommendation && <div className="mt-7 overflow-hidden rounded-[var(--card-radius)] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--card-shadow)]"><span className="inline-flex rounded-full bg-[var(--muted)] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-[var(--primary)]">{step.recommendation.label || "Recomendado"}</span><h2 className="mt-4 text-2xl font-extrabold tracking-[-.035em]">{step.recommendation.title}</h2><p className="mt-2 text-xs leading-5 text-[var(--muted-fg)]">{step.recommendation.description}</p><ul className="mt-5 space-y-2">{step.recommendation.benefits.map((item) => <li key={item} className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-5 place-items-center rounded-full bg-[var(--primary)] text-[var(--primary-fg)]"><Check size={12} /></span>{item}</li>)}</ul>{step.recommendation.deliverables && <div className="mt-5 flex flex-wrap gap-2">{step.recommendation.deliverables.map((item) => <span key={item} className="rounded-full border border-[var(--border)] px-3 py-1.5 text-[10px] font-bold text-[var(--muted-fg)]">{item}</span>)}</div>}</div>}
      <div className="mt-7"><SpecialBlocks step={step} /></div>
      {step.formFields && step.type === "form" && <form onSubmit={submitStep} className="mt-7 space-y-4">{step.formFields.map((field) => <div key={field.id}><label className="mb-2 block text-xs font-bold">{field.label}{field.required && <span className="text-[var(--primary)]"> *</span>}</label><FieldControl field={field} value={answers[field.key] || ""} onChange={(value) => updateAnswer(field.key, value)} onFocus={() => { if (!formStarted.current) { formStarted.current = true; event("form_started"); } }} /></div>)}<button type="submit" disabled={!formReady()} className="focus-ring flex min-h-13 w-full items-center justify-center gap-2 rounded-[var(--button-radius)] bg-[var(--primary)] px-5 text-sm font-extrabold text-[var(--primary-fg)] shadow-lg">{step.options?.[0]?.label || "Continuar"}<ArrowRight size={17} /></button></form>}
      {leadForm && step.formFields && <div className="mt-7 rounded-[var(--card-radius)] border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-extrabold">Receba os detalhes</h2><p className="mt-1 text-xs text-[var(--muted-fg)]">Preencha para nosso time continuar com contexto.</p><div className="mt-4 space-y-4">{step.formFields.map((field) => <div key={field.id}><label className="mb-2 block text-xs font-bold">{field.label}</label><FieldControl field={field} value={answers[field.key] || ""} onChange={(value) => updateAnswer(field.key, value)} onFocus={() => event("form_started")} /></div>)}</div><button onClick={submitLead} disabled={!formReady(step.formFields)} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-[var(--button-radius)] bg-[var(--primary)] text-sm font-extrabold text-[var(--primary-fg)]">Enviar e continuar <ArrowRight size={16} /></button></div>}
      {submitted ? <div className="mt-8 rounded-[var(--card-radius)] border border-[#bde7d6] bg-[#eaf8f2] p-5 text-[#176f53]"><span className="grid size-10 place-items-center rounded-full bg-[#15966c] text-white"><Check size={19} /></span><h2 className="mt-4 text-xl font-extrabold">Tudo certo!</h2><p className="mt-1 text-sm">Recebemos seus dados e o contexto da jornada.</p></div> : step.type !== "form" && !leadForm && <div className="mt-auto space-y-2 pt-7">{step.options?.map((option, index) => <button key={option.id} onClick={() => void optionClicked(option)} className={`focus-ring group flex min-h-[58px] w-full items-center gap-3 rounded-[var(--button-radius)] border px-4 text-left text-sm font-extrabold transition active:scale-[.985] ${index === 0 ? "border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-fg)] shadow-lg" : "border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)]"}`}><span className={`grid size-9 place-items-center rounded-xl ${index === 0 ? "bg-white/15" : "bg-[var(--muted)] text-[var(--primary)]"}`}><DynamicIcon name={option.icon} /></span><span className="flex-1"><span className="block">{option.label}</span>{option.description && <small className={`mt-0.5 block font-medium ${index === 0 ? "opacity-70" : "text-[var(--muted-fg)]"}`}>{option.description}</small>}</span><ChevronRight size={18} className="transition group-hover:translate-x-1" /></button>)}</div>}
    </motion.div></AnimatePresence></main>
    <footer className="relative px-5 pb-4 text-center text-[10px] font-semibold text-[var(--muted-fg)]">Experiência criada com <span className="font-extrabold text-[var(--primary)]">SmartBio</span></footer>
  </div>;
}

export function PublicExperience({ slug, preview = false }: { slug: string; preview?: boolean }) {
  const [project, setProject] = useState<Project | null>();
  useEffect(() => { setProject(localStore.getProject(slug) || null); }, [slug]);
  if (project === undefined) return <div className="grid min-h-screen place-items-center bg-[#f7f7fa]"><LoaderCircle className="animate-spin text-[#6d5ef5]" /></div>;
  if (!project || (!preview && project.status !== "published")) return <div className="grid min-h-screen place-items-center bg-[#f7f7fa] p-6 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e9e6ff] text-[#5f52d6]"><Compass /></span><h1 className="mt-5 text-2xl font-extrabold">Experiência indisponível</h1><p className="mt-2 text-sm text-[#74747e]">O endereço não existe ou ainda não foi publicado.</p><Link href="/" className="mt-6 inline-flex font-bold text-[#5f52d6]">Conhecer a SmartBio</Link></div></div>;
  return <div className="min-h-screen" style={{ background: project.designSystem.colors.background }}><div className={preview ? "mx-auto h-full max-w-md" : "mx-auto min-h-screen w-full max-w-[560px] shadow-[0_0_80px_rgba(0,0,0,.12)]"}><ExperienceCanvas project={project} preview={preview} /></div></div>;
}
