import { z } from "zod";
import { generateCopySuggestions, regenerateStep, regenerateVisualDirection } from "@/server/ai-editing/ai-editing-service";
import { aiSetupService } from "@/server/ai-setup/ai-setup-service";
import { setupApiError } from "@/server/ai-setup/setup-api";
import { apiError, apiSuccess } from "@/server/http/api-response";
import { withAuthenticatedActor } from "@/server/http/with-authenticated-actor";
import { applyRateLimitHeaders, consumeRateLimit, rateLimitRules } from "@/server/rate-limit/rate-limit";
const schema = z.object({ scope: z.enum(["business_analysis", "journey", "step", "copy", "visual_direction", "brand_system"]), projectId: z.uuid().optional(), stepId: z.string().optional(), fieldPath: z.string().optional(), currentValue: z.string().optional(), instruction: z.string().max(500).optional(), protectedFields: z.array(z.string()).max(100).optional() });
export const POST = withAuthenticatedActor(async (request, context: RouteContext<"/api/ai/setup/[sessionId]/regenerate">, actor) => { const rate = await consumeRateLimit("ai-setup-regenerate", actor.userId, rateLimitRules.aiRegenerate, { failClosed: true }); if (!rate.allowed) return applyRateLimitHeaders(apiError("Limite de regenerações atingido.", 429, "rate_limited"), rate); try { const { sessionId } = await context.params; const input = schema.parse(await request.json()); if (input.scope === "business_analysis") return applyRateLimitHeaders(apiSuccess(await aiSetupService.analyze(actor, sessionId)), rate); if (input.scope === "journey") return applyRateLimitHeaders(apiSuccess(await aiSetupService.generate(actor, sessionId)), rate); if (!input.projectId) return apiError("projectId é obrigatório para este escopo.", 422, "validation_error"); if (input.scope === "step") { if (!input.stepId) return apiError("stepId é obrigatório.", 422, "validation_error"); return applyRateLimitHeaders(apiSuccess(await regenerateStep(actor, input.projectId, input.stepId, { instruction: input.instruction })), rate); } if (input.scope === "copy") { if (!input.fieldPath || !input.currentValue) return apiError("fieldPath e currentValue são obrigatórios.", 422, "validation_error"); return applyRateLimitHeaders(apiSuccess(await generateCopySuggestions(actor, { projectId: input.projectId, stepId: input.stepId, fieldPath: input.fieldPath, currentValue: input.currentValue, action: "improve", customInstruction: input.instruction })), rate); } return applyRateLimitHeaders(apiSuccess(await regenerateVisualDirection(actor, input.projectId, { instruction: input.instruction || "Melhorar o visual" })), rate); } catch (error) { return setupApiError(error); } });
