"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, CircleDollarSign, Download, Filter, Target, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { buildConversionAnalytics } from "@/server/analytics/conversion-analytics";
import { comparePeriods } from "@/features/analytics/period-comparison";
import { backfillConversionGoals } from "@/features/conversion-goals/utils";
import { commercialRepository } from "@/lib/repositories/commercial-repository";
import { projectRepository } from "@/lib/repositories/project-repository";
import { localStore } from "@/lib/local-store";
import { isSupabaseConfigured } from "@/lib/supabase/client";
import { downloadCsv, formatNumber } from "@/lib/utils";
import type { AnalyticsEvent, CommercialOpportunity, Project } from "@/types";

type Overview = ReturnType<typeof buildConversionAnalytics>;
function startOfPeriod(days: number, offset = 0) { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - days * offset - (days - 1)); return date; }
export function AnalyticsDashboard({ projectId }: { projectId: string }) {
  const [project, setProject] = useState<Project | null>(); const [events, setEvents] = useState<AnalyticsEvent[]>([]); const [opportunities, setOpportunities] = useState<CommercialOpportunity[]>([]); const [remoteOverview, setRemoteOverview] = useState<Overview | null>(); const [days, setDays] = useState(7); const [goalId, setGoalId] = useState("all"); const [entryId, setEntryId] = useState("all"); const [destinationId, setDestinationId] = useState("all"); const [campaign, setCampaign] = useState("all");
  useEffect(() => { void projectRepository.getProject(projectId).then(async (found) => { setProject(found || null); if (!found) return; if (isSupabaseConfigured()) return; const tracked = await commercialRepository.getEvents(projectId); setEvents(tracked); setOpportunities(localStore.getOpportunities(projectId)); }).catch(() => setProject(null)); }, [projectId]);
  useEffect(() => { if (!project || !isSupabaseConfigured()) return; const from = startOfPeriod(days).toISOString(); const params = new URLSearchParams({ from }); if (goalId !== "all") params.set("goal", goalId); if (entryId !== "all") params.set("entry", entryId); if (destinationId !== "all") params.set("destination", destinationId); if (campaign !== "all") params.set("campaign", campaign); setRemoteOverview(undefined); void fetch(`/api/projects/${project.id}/analytics/overview?${params}`).then((response) => response.json()).then((payload: { data?: Overview }) => setRemoteOverview(payload.data || null)); }, [campaign, days, destinationId, entryId, goalId, project]);
  const goals = useMemo(() => project ? backfillConversionGoals(project) : [], [project]); const entries = useMemo(() => project?.entryPoints || [], [project]); const destinations = project?.commercialConfig?.routingDestinations || [];
  const currentEvents = useMemo(() => events.filter((event) => new Date(event.createdAt) >= startOfPeriod(days) && (goalId === "all" || event.conversionGoalId === goalId) && (entryId === "all" || event.entryPointId === entryId) && (destinationId === "all" || event.destinationId === destinationId) && (campaign === "all" || event.utmCampaign === campaign)), [campaign, days, destinationId, entryId, events, goalId]);
  const currentOpportunities = useMemo(() => opportunities.filter((item) => new Date(item.createdAt) >= startOfPeriod(days) && (goalId === "all" || item.conversionGoalId === goalId) && (entryId === "all" || item.entryPointId === entryId) && (destinationId === "all" || item.destinationId === destinationId) && (campaign === "all" || item.attribution?.campaign === campaign)), [campaign, days, destinationId, entryId, goalId, opportunities]);
  const localOverview = useMemo(() => buildConversionAnalytics({ events: currentEvents, opportunities: currentOpportunities, goals, entries, pages: project?.presence?.pages }), [currentEvents, currentOpportunities, entries, goals, project?.presence?.pages]); const overview = isSupabaseConfigured() ? remoteOverview : localOverview;
  const previousSessions = new Set(events.filter((event) => { const date = new Date(event.createdAt); return date >= startOfPeriod(days, 1) && date < startOfPeriod(days); }).map((event) => event.sessionId)).size; const comparison = overview ? comparePeriods(overview.sessions, previousSessions) : null;
  const campaigns = [...new Set(events.map((event) => event.utmCampaign).filter(Boolean))] as string[];
  if (project === undefined || (isSupabaseConfigured() && remoteOverview === undefined && project)) return <div className="h-96 animate-pulse rounded-[24px] bg-white" />; if (!project || !overview) return <div className="rounded-[24px] bg-white p-10 text-center"><h1 className="font-extrabold">Negócio não encontrado</h1></div>;
  return <div className="animate-enter"><header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Link href={`/app/projects/${project.id}`} className="inline-flex items-center gap-2 text-xs font-bold text-[#74727d]"><ArrowLeft size={14} /> {project.name}</Link><h1 className="mt-4 text-3xl font-extrabold tracking-[-.045em]">Analytics de conversão</h1><p className="mt-2 text-sm text-[#74727d]">Atenção, intenção, ação, oportunidade e conversão confirmada.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-[#dedce5] bg-white p-1">{[[1, "Hoje"], [7, "7 dias"], [30, "30 dias"]].map(([value, label]) => <button key={String(value)} onClick={() => setDays(Number(value))} className={`rounded-lg px-3 py-2 text-xs font-bold ${days === value ? "bg-[#07172f] text-white" : "text-[#77747f]"}`}>{String(label)}</button>)}</div><Button variant="secondary" onClick={() => downloadCsv(`analytics-${project.slug}.csv`, [["etapa", "sessoes", "% atencao", "% anterior"], ...overview.funnel.map((stage) => [stage.label, stage.sessions, stage.rateFromAttention, stage.rateFromPrevious])])}><Download /> CSV</Button></div></header>
  <nav aria-label="Visões de analytics" className="mt-7 flex gap-1 overflow-x-auto rounded-[18px] border border-[#e2e0e7] bg-white p-1.5">{["Visão geral", "Funil", "Objetivos", "Entradas", "Páginas", "Destinos", "Campanhas"].map((label, index) => <a key={label} href={index === 0 ? "#overview" : index === 1 ? "#funnel" : index === 4 ? "#pages" : "#segments"} className={`min-h-10 whitespace-nowrap rounded-xl px-3 py-2.5 text-xs font-bold ${index === 0 ? "bg-[#07172f] text-white" : "text-[#6f6b77] hover:bg-[#f3f2f6]"}`}>{label}</a>)}</nav>
  <section id="segments" className="mt-4 rounded-[20px] border border-[#e2e0e7] bg-white p-4"><div className="flex items-center gap-2 text-xs font-bold text-[#77747f]"><Filter size={15} /> Segmentar</div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[["Meta", goalId, setGoalId, goals.map((item) => [item.id, item.name])], ["Entrada", entryId, setEntryId, entries.map((item) => [item.id, item.name])], ["Destino", destinationId, setDestinationId, destinations.map((item) => [item.id, item.label])], ["Campanha", campaign, setCampaign, campaigns.map((item) => [item, item])]].map(([label, value, setter, options]) => <select key={String(label)} aria-label={`Filtrar por ${String(label).toLowerCase()}`} value={String(value)} onChange={(event) => (setter as (value: string) => void)(event.target.value)} className="min-h-11 rounded-xl border border-[#e0dee6] bg-[#f8f7fa] px-3 text-xs font-semibold"><option value="all">{String(label)}: todas</option>{(options as string[][]).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select>)}</div></section>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Sessões", overview.sessions, Users, comparison?.label || "Sem comparação ainda"], ["Oportunidades", overview.opportunities, Target, "ações comerciais"], ["Conversões", overview.conversions, BarChart3, "confirmadas manualmente"], ["Valor confirmado", new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(overview.confirmedValue), CircleDollarSign, "somente conversões confirmadas"]].map(([label, value, Icon, note]) => { const StatIcon = Icon as typeof Users; return <div key={String(label)} className="rounded-[19px] border border-[#e2e0e7] bg-white p-5"><StatIcon size={17} className="text-[#0054fc]" /><strong className="mt-6 block text-3xl tracking-[-.04em]">{typeof value === "number" ? formatNumber(value) : String(value)}</strong><span className="mt-1 block text-xs font-semibold">{String(label)}</span><small className="mt-3 block text-[#85828d]">{String(note)}</small></div>; })}</div>
  <section id="funnel" className="mt-5 rounded-[24px] border border-[#e2e0e7] bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-extrabold">Funil real</h2><p className="mt-1 text-xs text-[#7b7882]">Sessões únicas por estágio; sem projeções entre etapas.</p></div><Link href={`/app/projects/${project.id}/opportunities`} className="text-xs font-bold text-[#0054fc]">Ver oportunidades <ArrowRight className="inline" size={14} /></Link></div><div className="mt-8 grid gap-3 lg:grid-cols-5">{overview.funnel.map((stage, index) => <div key={stage.key} className="relative rounded-[18px] bg-[#f5f4f7] p-4"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#797680]">{stage.label}</span><strong className="mt-7 block text-3xl">{stage.sessions}</strong><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#e4e1e9]"><div className="h-full rounded-full bg-[#0186fc]" style={{ width: `${Math.min(100, stage.rateFromAttention)}%` }} /></div><small className="mt-2 block text-[#77747f]">{stage.rateFromAttention}% da atenção</small>{index < overview.funnel.length - 1 ? <ArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden text-[#aaa6b1] lg:block" size={16} /> : null}</div>)}</div></section>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-[24px] border border-[#e2e0e7] bg-white p-5"><h2 className="font-extrabold">Por meta</h2><div className="mt-5 space-y-3">{overview.byGoal.length ? overview.byGoal.map((item) => <div key={item.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 rounded-[14px] bg-[#f6f5f8] p-3 text-xs"><strong>{item.name}</strong><span>{item.opportunities} oportunidades</span><span>{item.conversions} conversões</span></div>) : <p className="text-sm text-[#77747f]">Sem metas no período.</p>}</div></section><section className="rounded-[24px] border border-[#e2e0e7] bg-white p-5"><h2 className="font-extrabold">Por entrada</h2><div className="mt-5 space-y-3">{overview.byEntry.length ? overview.byEntry.map((item) => <div key={item.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 rounded-[14px] bg-[#f6f5f8] p-3 text-xs"><strong>{item.name}</strong><span>{item.sessions} sessões</span><span>{item.conversions} conversões</span></div>) : <p className="text-sm text-[#77747f]">Sem entradas no período.</p>}</div></section></div>
  <section id="pages" className="mt-5 rounded-[24px] border border-[#e2e0e7] bg-white p-5 sm:p-7"><div><h2 className="text-xl font-extrabold">Desempenho das páginas</h2><p className="mt-1 text-xs text-[#7b7882]">Visitas, intenção e resultado comercial por página e seção, somente com dados reais.</p></div>{overview.byPage.length ? <div className="mt-6 space-y-4">{overview.byPage.map((item) => <article key={item.id} className="rounded-[18px] border border-[#e5e3ea] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{item.name}</strong><span className="rounded-full bg-[#eaf3ff] px-2 py-1 text-[10px] font-black uppercase text-[#0054fc]">{item.type === "landing" ? "Landing" : item.type === "home" ? "Home" : "Página"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{[["Visitas", item.views], ["Intenções", item.intentions], ["CTAs", item.ctaClicks], ["Oportunidades", item.opportunities], ["Conversões", item.conversions], ["Valor confirmado", new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(item.confirmedValue)]].map(([label, value]) => <div key={String(label)}><dt className="text-[10px] font-bold uppercase tracking-[.1em] text-[#85818d]">{String(label)}</dt><dd className="mt-1 text-lg font-black">{String(value)}</dd></div>)}</dl><div className="mt-4 border-t border-[#eceaf0] pt-3"><p className="text-[10px] font-black uppercase tracking-[.1em] text-[#85818d]">Seções que originaram ação</p><div className="mt-2 flex flex-wrap gap-2">{overview.bySection.filter((section) => section.pageId === item.id && (section.ctaClicks || section.conversionStarts)).map((section) => <span key={section.id} className="rounded-lg bg-[#f5f4f7] px-2.5 py-1.5 text-xs font-bold">{section.name}: {section.ctaClicks} CTA · {section.conversionStarts} início</span>)}{!overview.bySection.some((section) => section.pageId === item.id && (section.ctaClicks || section.conversionStarts)) ? <span className="text-xs text-[#85818d]">Sem ações de seção no período.</span> : null}</div></div></article>)}</div> : <p className="mt-6 rounded-[16px] bg-[#f6f5f8] p-5 text-sm text-[#77747f]">Ainda não há páginas publicadas ou dados de visita neste período.</p>}</section></div>;
}
