import { z } from "zod";
import { after } from "next/server";
import { createWebsiteSource, processWebsiteSource } from "@/server/business-sources/source-service";
import { EntitlementError } from "@/server/entitlements/entitlement-types";
import { apiError } from "@/server/http/api-response";
import { withAuthenticatedActor } from "@/server/http/with-authenticated-actor";
import { applyRateLimitHeaders, consumeRateLimit, rateLimitRules } from "@/server/rate-limit/rate-limit";
const schema = z.object({ setupSessionId: z.uuid().optional(), projectId: z.uuid().optional(), url: z.url() });
export const runtime = "nodejs";
export const maxDuration = 120;
export const POST = withAuthenticatedActor(async (request, _context, actor) => { const rate = await consumeRateLimit("source-process", actor.workspaceId, rateLimitRules.sourceProcess, { failClosed: true }); if (!rate.allowed) return applyRateLimitHeaders(apiError("Limite de importações atingido.", 429, "rate_limited"), rate); try { const source = await createWebsiteSource(actor, schema.parse(await request.json())); after(async () => { try { await processWebsiteSource(actor, source.id); } catch { console.error("website_source_processing_failed", { sourceId: source.id }); } }); return applyRateLimitHeaders(Response.json({ data: { id: source.id, name: source.name, type: source.type, status: source.status } }, { status: 202 }), rate); } catch (error) { if (error instanceof EntitlementError) throw error; return applyRateLimitHeaders(apiError(error instanceof Error ? error.message : "Não foi possível importar o site.", 400, "website_import_failed"), rate); } });
