"use client";
import { Plus } from "lucide-react";
import { useState } from "react";
import { ReservationCalendar } from "@/components/commercial-data/reservations/reservation-calendar";
import { ReservationPolicyForm } from "@/components/commercial-data/reservations/reservation-policy-form";
import { ReservationPreview } from "@/components/commercial-data/reservations/reservation-preview";
import { ReservableUnitForm } from "@/components/commercial-data/reservations/reservable-unit-form";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { Project, ProjectPolicy, ReservationBlock, ReservableUnit } from "@/types";
type Patch = Partial<NonNullable<Project["commercialConfig"]>>;
export function ReservationsPanel({ projectId, units, blocks, policies, onChange }: { projectId: string; units: ReservableUnit[]; blocks: ReservationBlock[]; policies: ProjectPolicy[]; onChange: (value: Patch) => void }) { const [editing, setEditing] = useState<ReservableUnit | null>(null); const add = () => setEditing({ id: crypto.randomUUID(), projectId, name: "", capacityAdults: 1, capacityChildren: 0, quantity: 1, currency: "BRL", confirmationMode: "manual_approval", isActive: true, mediaAssetIds: [], amenities: [] }); const save = () => { if (!editing?.name.trim()) return; onChange({ reservableUnits: units.some((item) => item.id === editing.id) ? units.map((item) => item.id === editing.id ? editing : item) : [...units, editing] }); setEditing(null); }; const reservationPolicy = policies.find((item) => item.type === "reservation"); return <section className="flex flex-col gap-8"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-extrabold">Reservas</h2><p className="mt-1 text-sm text-[#74747e]">Unidades, capacidade, sinal, bloqueios e políticas.</p></div><Button onClick={add}><Plus data-icon="inline-start" />Nova unidade</Button></div><div className="grid gap-3 sm:grid-cols-2">{units.map((unit) => <button type="button" key={unit.id} onClick={() => setEditing(unit)} className="focus-ring rounded-[16px] border border-[#e5e4eb] p-4 text-left hover:border-[#0186fc]"><strong>{unit.name}</strong><p className="mt-1 text-xs text-[#777781]">{unit.quantity} disponível(is) · capacidade {unit.capacityAdults + unit.capacityChildren}</p></button>)}</div><ReservationCalendar projectId={projectId} units={units} blocks={blocks} onChange={(reservationBlocks) => onChange({ reservationBlocks })} /><ReservationPolicyForm projectId={projectId} policy={reservationPolicy} onChange={(policy) => onChange({ policies: reservationPolicy ? policies.map((item) => item.id === policy.id ? policy : item) : [...policies, policy] })} /><ReservationPreview units={units} /><Dialog open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null); }}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Unidade reservável</DialogTitle></DialogHeader>{editing ? <ReservableUnitForm value={editing} onChange={setEditing} /> : null}<DialogFooter><Button variant="danger" disabled={!editing || !units.some((item) => item.id === editing.id)} onClick={() => { if (editing) onChange({ reservableUnits: units.filter((item) => item.id !== editing.id) }); setEditing(null); }}>Excluir</Button><Button onClick={save}>Salvar unidade</Button></DialogFooter></DialogContent></Dialog></section>; }
