import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { createServiceClient } from "@/lib/supabase/server";
import { assertProjectAccess } from "@/server/auth/project-access";
import type { AuthenticatedActor } from "@/server/auth/setup-actor";
import { extractSourceFacts } from "@/server/business-sources/source-extractor";
import { parseSource } from "@/server/business-sources/source-parser";
import { sourceRepository } from "@/server/business-sources/source-repository";
import { importWebsite } from "@/server/business-sources/website-source";
import { notifyProjectEvent } from "@/server/notifications/notification-service";
import type { BusinessSource } from "@/types";

const MAX_FILE_SIZE = 15 * 1024 * 1024;
function cleanName(value: string) { return value.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-").slice(0, 180) || "material"; }
function detectedType(buffer: Buffer, name: string): { type: "pdf" | "image" | "csv" | "text"; mimeType: string } { if (buffer.subarray(0, 5).toString() === "%PDF-") return { type: "pdf", mimeType: "application/pdf" }; if (buffer.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) return { type: "image", mimeType: "image/png" }; if (buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) return { type: "image", mimeType: "image/jpeg" }; if (buffer.subarray(0, 4).toString() === "RIFF" && buffer.subarray(8, 12).toString() === "WEBP") return { type: "image", mimeType: "image/webp" }; if (buffer.subarray(0, Math.min(buffer.length, 4096)).includes(0)) throw new Error("Formato de arquivo não permitido."); const extension = name.toLowerCase().split(".").pop(); if (extension === "csv") return { type: "csv", mimeType: "text/csv" }; if (extension === "txt") return { type: "text", mimeType: "text/plain" }; throw new Error("Assinatura ou extensão de arquivo não permitida. Converta DOC/DOCX para PDF."); }
async function assertLinks(actor: AuthenticatedActor, projectId?: string, setupSessionId?: string) { if (projectId) await assertProjectAccess(actor, projectId, "write"); if (setupSessionId) { const client = createServiceClient(); if (!client) throw new Error("Supabase não configurado."); const { data } = await client.from("ai_setup_sessions").select("id").eq("id", setupSessionId).eq("workspace_id", actor.workspaceId).eq("created_by", actor.userId).maybeSingle(); if (!data) throw new Error("Sessão de onboarding não encontrada."); } }
async function finishProcessing(actor: AuthenticatedActor, source: BusinessSource, parsed: { text?: string; fileData?: string; mimeType?: string; metadata?: Record<string, unknown> }) { await sourceRepository.update(actor, source.id, { status: "processing", processing_error: null }); try { const extracted = await extractSourceFacts(actor, source, parsed); const facts = await sourceRepository.replaceFacts(actor, source, extracted.facts.map((fact) => ({ key: fact.key, type: fact.key.split(/[.[\]]/)[0] || "fact", value: fact.value, evidenceExcerpt: fact.evidenceExcerpt, confidence: fact.confidence, verificationStatus: fact.verificationStatus }))); const updated = await sourceRepository.update(actor, source.id, { status: "processed", extracted_text: parsed.text || null, extracted_data: { ...extracted, ...parsed.metadata, factCount: facts.length }, processing_error: null }); return { source: updated, facts }; } catch (error) { await sourceRepository.update(actor, source.id, { status: "failed", processing_error: error instanceof Error ? error.message.slice(0, 500) : "Falha no processamento." }); if (source.projectId) await notifyProjectEvent(source.projectId, "source.processing_failed", "business_source", source.id, { source: source.name }).catch(() => undefined); throw error; } }
export async function uploadBusinessSource(actor: AuthenticatedActor, file: File, input: { projectId?: string; setupSessionId?: string }) { if (actor.persistence === "memory") throw new Error("Configure o Supabase para enviar arquivos privados."); await assertLinks(actor, input.projectId, input.setupSessionId); if (!file.size || file.size > MAX_FILE_SIZE) throw new Error("O arquivo deve ter no máximo 15 MB."); const buffer = Buffer.from(await file.arrayBuffer()); const detected = detectedType(buffer, file.name); const id = randomUUID(); const name = cleanName(file.name); const path = `${actor.workspaceId}/${id}/${name}`; const checksum = createHash("sha256").update(buffer).digest("hex"); const source = await sourceRepository.create(actor, { id, projectId: input.projectId, setupSessionId: input.setupSessionId, type: detected.type, name, storagePath: path, mimeType: detected.mimeType, fileSize: buffer.byteLength, checksum }); const client = createServiceClient()!; const { error } = await client.storage.from("business-sources").upload(path, buffer, { contentType: detected.mimeType, upsert: false }); if (error) { await sourceRepository.update(actor, id, { status: "failed", processing_error: "Falha ao salvar o arquivo privado." }); throw new Error("Não foi possível armazenar o arquivo."); } await sourceRepository.update(actor, id, { status: "uploaded" }); return finishProcessing(actor, source, await parseSource(buffer, detected.type, detected.mimeType)); }
export async function importWebsiteSource(actor: AuthenticatedActor, input: { url: string; projectId?: string; setupSessionId?: string }) { if (actor.persistence === "memory") throw new Error("Configure o Supabase para importar sites com rastreabilidade."); await assertLinks(actor, input.projectId, input.setupSessionId); const imported = await importWebsite(input.url); const source = await sourceRepository.create(actor, { id: randomUUID(), projectId: input.projectId, setupSessionId: input.setupSessionId, type: "website", name: new URL(input.url).hostname, sourceUrl: input.url }); return finishProcessing(actor, source, { text: imported.text, metadata: { pages: imported.pages.map((page) => page.url) } }); }
