import "server-only";
import { createServiceClient } from "@/lib/supabase/server";
import type { AuthenticatedActor } from "@/server/auth/setup-actor";
import type { BusinessSource, BusinessSourceFact } from "@/types";

function database() { const client = createServiceClient(); if (!client) throw new Error("Configure o Supabase para usar fontes privadas."); return client; }
function sourceFromRow(row: Record<string, unknown>): BusinessSource { return { id: String(row.id), workspaceId: String(row.workspace_id), projectId: row.project_id ? String(row.project_id) : undefined, setupSessionId: row.setup_session_id ? String(row.setup_session_id) : undefined, type: row.source_type as BusinessSource["type"], name: String(row.name), sourceUrl: row.source_url ? String(row.source_url) : undefined, storagePath: row.storage_path ? String(row.storage_path) : undefined, mimeType: row.mime_type ? String(row.mime_type) : undefined, fileSize: row.file_size == null ? undefined : Number(row.file_size), checksum: row.checksum ? String(row.checksum) : undefined, status: row.status as BusinessSource["status"], extractedText: row.extracted_text ? String(row.extracted_text) : undefined, extractedData: (row.extracted_data || {}) as Record<string, unknown>, processingError: row.processing_error ? String(row.processing_error) : undefined, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function factFromRow(row: Record<string, unknown>): BusinessSourceFact { return { id: String(row.id), sourceId: String(row.source_id), projectId: row.project_id ? String(row.project_id) : undefined, key: String(row.fact_key), type: String(row.fact_type), value: row.fact_value, evidenceExcerpt: row.evidence_excerpt ? String(row.evidence_excerpt) : undefined, confidence: row.confidence == null ? undefined : Number(row.confidence), verificationStatus: row.verification_status as BusinessSourceFact["verificationStatus"], appliedAt: row.applied_at ? String(row.applied_at) : undefined, createdAt: String(row.created_at) }; }

export const sourceRepository = {
  async create(actor: AuthenticatedActor, input: { id: string; projectId?: string; setupSessionId?: string; type: BusinessSource["type"]; name: string; sourceUrl?: string; storagePath?: string; mimeType?: string; fileSize?: number; checksum?: string }) { const { data, error } = await database().from("business_sources").insert({ id: input.id, workspace_id: actor.workspaceId, project_id: input.projectId || null, setup_session_id: input.setupSessionId || null, source_type: input.type, name: input.name, source_url: input.sourceUrl || null, storage_path: input.storagePath || null, mime_type: input.mimeType || null, file_size: input.fileSize ?? null, checksum: input.checksum || null, status: input.storagePath ? "uploaded" : "pending", created_by: actor.userId }).select("*").single(); if (error) throw new Error("Não foi possível registrar a fonte."); return sourceFromRow(data); },
  async get(actor: AuthenticatedActor, id: string) { const { data, error } = await database().from("business_sources").select("*").eq("id", id).eq("workspace_id", actor.workspaceId).maybeSingle(); if (error) throw new Error("Não foi possível carregar a fonte."); return data ? sourceFromRow(data) : null; },
  async list(actor: AuthenticatedActor, projectId?: string, setupSessionId?: string) { let query = database().from("business_sources").select("*").eq("workspace_id", actor.workspaceId).order("created_at", { ascending: false }); if (projectId) query = query.eq("project_id", projectId); if (setupSessionId) query = query.eq("setup_session_id", setupSessionId); const { data, error } = await query; if (error) throw new Error("Não foi possível listar as fontes."); return (data || []).map(sourceFromRow); },
  async update(actor: AuthenticatedActor, id: string, patch: Record<string, unknown>) { const { data, error } = await database().from("business_sources").update(patch).eq("id", id).eq("workspace_id", actor.workspaceId).select("*").single(); if (error) throw new Error("Não foi possível atualizar a fonte."); return sourceFromRow(data); },
  async replaceFacts(actor: AuthenticatedActor, source: BusinessSource, facts: Array<{ key: string; type: string; value: unknown; evidenceExcerpt?: string; confidence?: number; verificationStatus: BusinessSourceFact["verificationStatus"] }>) { const client = database(); const { error: deleteError } = await client.from("business_source_facts").delete().eq("source_id", source.id); if (deleteError) throw new Error("Não foi possível atualizar os fatos extraídos."); if (!facts.length) return []; const { data, error } = await client.from("business_source_facts").insert(facts.map((fact) => ({ source_id: source.id, project_id: source.projectId || null, fact_key: fact.key, fact_type: fact.type, fact_value: fact.value, evidence_excerpt: fact.evidenceExcerpt || null, confidence: fact.confidence ?? null, verification_status: fact.verificationStatus }))).select("*"); if (error) throw new Error("Não foi possível registrar os fatos extraídos."); return (data || []).map(factFromRow); },
  async listFacts(actor: AuthenticatedActor, sourceId: string) { const source = await this.get(actor, sourceId); if (!source) throw new Error("Fonte não encontrada."); const { data, error } = await database().from("business_source_facts").select("*").eq("source_id", sourceId).order("created_at"); if (error) throw new Error("Não foi possível listar os fatos."); return (data || []).map(factFromRow); },
  async updateFact(actor: AuthenticatedActor, sourceId: string, factId: string, input: { value?: unknown; status: BusinessSourceFact["verificationStatus"] }) { const source = await this.get(actor, sourceId); if (!source) throw new Error("Fonte não encontrada."); const patch: Record<string, unknown> = { verification_status: input.status }; if (input.value !== undefined) patch.fact_value = input.value; const { data, error } = await database().from("business_source_facts").update(patch).eq("id", factId).eq("source_id", sourceId).select("*").single(); if (error) throw new Error("Não foi possível revisar o fato."); return factFromRow(data); },
};
