import { z } from "zod";
import { activationEligibilitySchema } from "./activation-eligibility.schema";
import { activationLimitsSchema } from "./activation.schema";
import type { ActivationEligibility,ActivationLimits,ActivationOffer,ActivationPlacement,ConversionActivation } from "./activation.types";

const offerSchema=z.object({id:z.string().uuid(),activationId:z.string().uuid(),offerType:z.enum(["percentage_discount","fixed_discount","free_shipping","special_price","free_item","bonus","coupon","no_discount"]),label:z.string(),description:z.string().optional(),percentage:z.number().optional(),amount:z.number().optional(),specialPrice:z.number().optional(),currency:z.string().length(3),minSubtotal:z.number().optional(),maxDiscount:z.number().optional(),scope:z.record(z.string(),z.unknown()),benefitConfig:z.record(z.string(),z.unknown()),isActive:z.boolean(),createdAt:z.string().optional(),updatedAt:z.string().optional()});
const placementSchema=z.object({id:z.string().uuid(),activationId:z.string().uuid(),presencePageId:z.string().uuid().optional(),presenceSectionId:z.string().uuid().optional(),placementType:z.enum(["announcement_bar","hero_override","section_badge","product_badge","service_badge","conversion_cta","journey_banner","floating_cta"]),content:z.record(z.string(),z.unknown()),style:z.record(z.string(),z.unknown()),priority:z.number().int(),isActive:z.boolean()});
export const publishedActivationSnapshotSchema=z.object({snapshotVersion:z.literal(1),activationId:z.string().uuid(),activationVersion:z.number().int().positive(),activationKey:z.string(),name:z.string(),activationType:z.enum(["promotion","launch","fill_calendar","lead_capture","product_push","service_push","location_push","waitlist","seasonal","announcement","custom"]),conversionGoalId:z.string().optional(),defaultDestinationId:z.string().optional(),destinationMode:z.enum(["routing","fixed_destination","goal_default","native"]),title:z.string().optional(),message:z.string().optional(),requiresIdentity:z.boolean(),identityMode:z.enum(["none","phone","email","phone_or_email"]),identityVerification:z.enum(["none","otp"]),completionChannel:z.enum(["native","whatsapp","external_url","email","phone"]).optional(),startsAt:z.string().optional(),endsAt:z.string().optional(),timezone:z.string(),priority:z.number().int(),eligibility:activationEligibilitySchema,limits:activationLimitsSchema,settings:z.record(z.string(),z.unknown()),offers:z.array(offerSchema),placements:z.array(placementSchema),entryPointIds:z.array(z.string().uuid()),locationIds:z.array(z.string().uuid())});
export interface PublishedActivationSnapshot{snapshotVersion:1;activationId:string;activationVersion:number;activationKey:string;name:string;activationType:ConversionActivation["activationType"];conversionGoalId?:string;defaultDestinationId?:string;destinationMode:"routing"|"fixed_destination"|"goal_default"|"native";title?:string;message?:string;requiresIdentity:boolean;identityMode:ConversionActivation["identityMode"];identityVerification:"none"|"otp";completionChannel?:ConversionActivation["completionChannel"];startsAt?:string;endsAt?:string;timezone:string;priority:number;eligibility:ActivationEligibility;limits:ActivationLimits;settings:ConversionActivation["settings"];offers:ActivationOffer[];placements:ActivationPlacement[];entryPointIds:string[];locationIds:string[]}
