"use client";
import { Plus } from "lucide-react";
import { useState } from "react";
import { DestinationForm } from "@/components/commercial-data/destinations/destination-form";
import { PaymentDestinationForm } from "@/components/commercial-data/destinations/payment-destination-form";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { Project, RoutingDestination } from "@/types";
type Patch = Partial<NonNullable<Project["commercialConfig"]>>;
export function DestinationsPanel({ destinations, paymentUrl, onChange }: { destinations: RoutingDestination[]; paymentUrl?: string; onChange: (value: Patch) => void }) { const [editing, setEditing] = useState<RoutingDestination | null>(null); const add = () => setEditing({ id: crypto.randomUUID(), key: "", type: "whatsapp", label: "", value: "" }); const valid = (destination: RoutingDestination) => destination.label.trim() && (destination.type === "unavailable" || Boolean(destination.value?.trim())); const save = () => { if (!editing || !valid(editing)) return; onChange({ routingDestinations: destinations.some((item) => item.id === editing.id) ? destinations.map((item) => item.id === editing.id ? editing : item) : [...destinations, editing] }); setEditing(null); }; return <section className="flex flex-col gap-8"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-extrabold">Destinos e pagamentos</h2><p className="mt-1 text-sm text-[#74747e]">Canais reais para concluir a próxima ação comercial.</p></div><Button onClick={add}><Plus data-icon="inline-start" />Novo destino</Button></div><div className="grid gap-3 sm:grid-cols-2">{destinations.map((destination) => <button type="button" key={destination.id} onClick={() => setEditing(destination)} className="focus-ring rounded-[16px] border border-[#e5e4eb] p-4 text-left hover:border-[#8f84f7]"><span className="text-xs font-extrabold uppercase tracking-[.12em] text-[#6658d9]">{destination.type}</span><strong className="mt-1 block">{destination.label}</strong><p className="mt-1 truncate text-xs text-[#777781]">{destination.value || "Fallback sem destino externo"}</p></button>)}</div><PaymentDestinationForm value={paymentUrl} onChange={(next) => onChange({ paymentUrl: next })} /><Dialog open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null); }}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Destino comercial</DialogTitle></DialogHeader>{editing ? <DestinationForm value={editing} onChange={setEditing} /> : null}<DialogFooter><Button variant="danger" disabled={!editing || !destinations.some((item) => item.id === editing.id)} onClick={() => { if (editing) onChange({ routingDestinations: destinations.filter((item) => item.id !== editing.id) }); setEditing(null); }}>Excluir</Button><Button onClick={save}>Salvar destino</Button></DialogFooter></DialogContent></Dialog></section>; }
